### ISSUE TITLE
Host Override doesn't work with ip port

### ISSUE THREAD

**Issue by willems28** [NLnetLabs/unbound#1000]
**Describe the bug**
I am trying to do a host override in Unbound DNS on OPNsense. I have done other redirects but with out port numbers and they work fine. When I try to create a host redirect with an ip address and port number, like 10.10.20.05:5959, I get "please specify a valid network segment or address (IPv4/IPv6)" in red.

**To reproduce**
1. Add an ip address WITH port on Edit Host Override dialog screen.
2.
3.

**Comment by gthess** [comment]
Hi there,

I am not familiar with the OPNsense interface but if they pass values as-is to Unbound you could try Unbound's `ip@port` notation, since Unbound does support specifying custom ports.
If that doesn't work I cannot help you further and it would be best to open an issue with OPNsense instead.
Actually opening an issue to document the expected notation in the interface (if that is not already there) would be an appreciated move!
