### ISSUE TITLE
[FR] Add support for valkey

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#1036]
Realizing it's early days, but now that the [Linux Foundation](https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community) officially launched [valkey](https://github.com/valkey-io/valkey), my first thought was to replace unbound's redis backend with it.

Any plans/roadmap on the horizon?

**Comment by wcawijngaards** [comment]
Unbound uses the libhiredis library for the cachedb module. That is a C client interface. It seems to be in the valkey repo at valkey/deps/hiredis.

I would think that it would work straight away. Since it is a copy of the externally developed hiredis library and that is what unbound uses, I guess that would work without needing changes in Unbound. Unbound has support to be able to support different backends for the cachedb module. It can be configured with the `backend: "redis"` option in the `cachedb:` section of the config.

**Comment by ghost** [comment]
Thank you for the heads-up. I actually already use the redis backend on my Arch Linux box. Works fine. Leaving it up to the Arch Linux package manager for [hiredis](https://archlinux.org/packages/extra/x86_64/hiredis/) if they want to change to the valkey repo or not.

Regards
