### ISSUE TITLE
I think libevent for unbound is broken and cannot be compiled

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1075]
Whenever I try to compile unbound with --with-libevent I get an error that it cannot find libevent. Unfortunately I don't have any more logs that I could upload, but where is my mistake when I say ./configure --with-libevent ? I think it's a bug in unbound 1.20.0, if it isn't then I don't know what is.

best regards

**Comment by wcawijngaards** [comment]
There is output for what ./configure did, in `config.log`. This file has some text at the start, and then the output in detail for each of the tests that configure printed a line about. After that there are some summary lists, with like detected variables and output directives.

So, could you look in the `config.log` file? In there search for the part where it did the libevent tests. Then it gives detailed output. Frequently that is a compiler command, perhaps a fairly long example program that it is trying to compile. And then also the error output that the compile produced. That can tell what the problem was. Also the output of the configure command to the console, the part where it did the tests could be useful.

For a compile --with-libevent to work, libevent needs to be installed with the software development package. Thus not only the library, but also the include header files. Frequently package systems call it like, libevent-dev, or libevent-devel or something. If that was missing, the output would be that libevent cannot be found. The other case could be that libevent is installed in a different location, like on mac packagers, and --with-libevent=path is then a way to tell where it can be found.

By default unbound's configure looks for libevent in /usr/local /opt/local /usr/lib /usr/pkg /usr/sfw and /usr. It searches for include/event.h or include/event2/event.h to find the header files for libevent.

**Comment by Aura67** [comment]
Yes, I found my mistake, I just had to install the libevent from debian as you already wrote, this package had the name: libev-libevent-dev, then it worked without errors and unbound is running with all ports, it's damn quick, I have it in the guide then I just deactivated the other two things or rather made libevent executable without them so that it can't interfere with each other. Thank you for the answer, I'll close my problem with that
