### ISSUE TITLE
DNS Over tls with Unbound secure question

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1107]
Hi, I have a question because I don't quite understand it. If I set up Unbound to use DNS Over TLS, I'm thinking of Swiss data protection quad9 with 9.9.9.9, will all my requests be encrypted over port 853? Because it says that the requests are only encrypted to the upstream server. And actually, Unbound does make requests to the root server? But unfortunately over port 53, which cannot be encrypted. Hence the question of whether it is possible to activate DNS over TLS? With a forward zone. thanks for the answer in advance.

and I don't understand this option here: forward-no-cache: no what does the option do if you use quad9 for example and have set it to no because it says yes if it is set to yes no answers are cached or are answers not cached if it is set to no?

sry, I know it's a problem reporter here on github, but otherwise everything works for me, the only question I have is

**Comment by wcawijngaards** [comment]
If the set up is to send all queries to the upstream, and sets up to send it all with dns over tls, then all queries are encrypted and on port 853. Mostly for forwarders to a public resolver all queries are then send there. Then there are no requests to the root servers, because queries are sent to the public resolver.

That forwarder-no-cache would cause every query to be not cached, if enabled, for a forwarder that sends all traffic to an upstream public resolver. So, leave it out, or at "no", and then caching is enabled, would be the default choice.

There is a configuration example on this page, that explains to enable dns over tls to a public dns provider
https://nlnetlabs.nl/news/2018/May/03/unbound-1.7.1-released/

The man page on the tls upstream for forwarder and forwarder documentation
https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-forward-forward-tls-upstream
https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-forward-forward-addr

**Comment by Aura67** [comment]
So I understand you can't bypass port 53 if unbound stands alone and as far as I know you can't encrypt requests locally but I also said :forward-first: no, I think that means that Unbound tries to answer the request first? this is the last question because you don't need SSL but I have installed with SSL.

**Comment by wcawijngaards** [comment]
No, forward-first is about other configuration and fallback to recursion, I think it is better left off, at its default.

Unbound has a cache so tries to answer from that first, before asking the upstream servers. The local-zone and local-data is also consulted first, before asking the upstream, and before looking at the cache.

**Comment by Aura67** [comment]
OK, thanks, then I have the unbound cache + port 853 from quad9. I think the data protection is very good. You say yourself that you have no requests or that you see the requests and so no third party can read the stuff that I send. Thank you, I'm looking forward to unbound version 1.20.1, good work.
