### ISSUE TITLE
I wonder if it makes sense for me h2/h3 is displayed in my request

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1121]
Hello, there is one thing I don't understand. I'm wondering if these options make sense for me:

http-nodelay:

http-query-buffer-size:

http-response-buffer-size:

since I use a forwarder DNS over TLS, the wiki only says that it is for port 443 and TLS has port 853.
And my Unbound port is: 5335 and not 443. but in my DNS request it shows: h2/h3

**Comment by wcawijngaards** [comment]
It is possible to send the traffic over any port number that is configured. The config can set the port numbers used. The defaults are the usual values, the same as the wiki says. It is otherwise fine to run Unbound on a different port and then accept traffic and configure what type of traffic.

The options for http settings are not changing the port numbers. Those set the memory in use and the nodelay socket option, that changes how the traffic is sent, if it waits for more data.

**Comment by Aura67** [comment]
OK, good to know. I also found out that if I want to use the ech sni with unbound, which has tls so that nobody can intercept the handshakes, I just have to write DNS-over-TLS under server and then the port number without @ and then just mark it with @ for forward upstream, but if I enter http-notls-downstream in my config, then unbound sees the ech sni exactly like that. But is there any way to set it up so that you can go over https in firefox with unbound? So far it's only worked with other doh clients.

**Comment by wcawijngaards** [comment]
There are no sni options for downstream service, there is a tls option for sni to the upstream. I thought it would not matter and without an SNI option, the downstream connections would work regardless of the sni setting by the downstream client. I have not heard others say how to make it work with firefox.

**Comment by Aura67** [comment]
I now simply add port 853 and tell Firefox to use it. I simply set the option use sni in Unbound and then port 853 should do the job. Thanks for your update, I've already installed it today.
