### ISSUE TITLE
compiling fails with --with-libngtcp2

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1158]
Hello, how do I install Unbound with DNS Over QUIC without it failing? Is there a program under apt that will enable Unbound to find DNS Over QUIC like libnghttp2? thanks for help :)

**Comment by wcawijngaards** [comment]
The library is not available in that way. That means compiling unbound, with specific downloads of libngtcp2, and also of openssl+quic. There are more detailed compile instructions elsewhere, https://blog.nlnetlabs.nl/dns-over-quic-in-unbound/ .

**Comment by Aura67** [comment]
In the unbound version 1.22.0 it says that this option: harden-unverified-glue: yes should protect unbound if you use a different zone. I assume that means something like a dot upstream server and if so, what exactly does the option do in Unbound? And thanks for the update, unbound has become faster. I added the option: harden-unverified-glue: yes to my unbound config. It doesn't affect dot.

**Comment by wcawijngaards** [comment]
It is for use when unbound is performing recursion, so that is not with config to forward the queries. Then it protects against misregistered glue information, by looking up glue that is not inside the zone that is being looked up. This stops old or wrong glue that is in the parent zone from misdirecting traffic for the subordinate zone. The glue that is allowed is the strict or narrow glue that is in-zone. It takes lookup queries, and falls back to the original information if the other sources do not have a response.

When the server config sends all traffic with a forward declaration to another server, the item does not have an impact, since there are no delegations to follow.

**Comment by Aura67** [comment]
good option for unbound then I did everything right and activated it so that I don't get any wrong data or if I get a server failure from unbound because of forward-first: no because unbound then does its work itself thank you
