### ISSUE TITLE
Typos in unbound.conf documentation

### ISSUE THREAD

**Issue by sunbearc22** [NLnetLabs/unbound#1163]
1. Is there a typo in [unbound.conf](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html) for the default value of the `harden-short-bufsize` argument. I think its default value should be` no` and not `on`.

   ![unbound conf_documentation_typo](https://github.com/user-attachments/assets/959dfef1-5acd-4178-8372-35b3b2a1cae2)

2. Also see this:
   ![image](https://github.com/user-attachments/assets/d90f639b-459f-4101-b9b2-3f8b0da2f90d)  
   The argument for `caps-whitelist` should not be `<yes or no>` but should be `<domain>`.

3. Another:
   ![image](https://github.com/user-attachments/assets/f118d428-a648-4717-93ac-e19504d2becc)
   The argument for `ipsecmod-whitelist` should not be `<yes or no>` but should be `<domain>`.

**Comment by gthess** [comment]
Thanks for these!
The default value for `harden-short-bufsize` should actually be `yes`. It is currently on because of the notion of on/off. But it is indeed confusing. I changed that and `harden-large-queries` below to use the available values instead.

I see you are still editing, so I will wait with committing (and closing the issue) until you give a signal that you have finished with reviewing the man page :)

**Comment by sunbearc22** [comment]
@gthess Is the default value of `harden-large-queries` `yes` or `no`? It states that it should be off and writes `no`. So should it be `yes`? I did not quite understand it. What does `harden` mean?

**Comment by sunbearc22** [comment]
@gthess BTW, is there an unbound forum where I can post my question on setting up `unbound.conf` and on how unbound works. Posting in Github issue seems inappropriate as they are questions on using unbound.   

I have finished posting my edits. ;)

Below doc shows my condensed summary of `unbound.conf` arguments and their default values: 
[unbound.conf_arguments_and_default_values.txt](https://github.com/user-attachments/files/17525263/unbound.conf_arguments_and_default_values.txt)
Are they correct?

**Comment by gthess** [comment]
The default value of `harden-large-queries` is indeed `no`. I changed the text to not use `off`. Harden is a term regularly used in security and means to fortify with (additional) security settings.

You can use the official mailing list to post questions about operating Unbound (https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users)

You can find a similar document in the source code of Unbound (https://github.com/NLnetLabs/unbound/blob/master/doc/example.conf.in). This lists the default values for the options where it makes sense; otherwise provides an example configuration value. After installation this file can be found at `doc/example.conf`. Not sure if it is included with system packages though.

I have committed the documentation changes in the source code but the online documentation follows the latest release. So it will be updated when the new version is released.
