### ISSUE TITLE
Question about option prefetch: yes serve-expired: yes

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1192]
Hello, what I was wondering is if I use these two options here in Unbound: prefetch: yes
serve-expired: yes and have a dns over tls upstream is it okay or should I set it to prefetch: yes? Because I want to have old dns answers that are in the cache so that the answer is there faster.

thanks for an answer

Greetings Aura

**Comment by gthess** [comment]
Hi Aura, I don't fully understand your question but I'll try to answer :)

`prefetch` and `serve-expired` can be used independently from each other.

`prefetch` will try to update a cached record when a **cached reply** happens at the last 10% of the record's original TTL.

`serve-expired` will allow Unbound to serve expired answers.
This can happen before resolution is attempted (`serve-expired-client-timeout: 0`), or after a resolution attempt if the resolution takes too much time (`serve-expired-client-timeout: <too-much-time-in-milliseconds>`).

`prefetch` is pretty harmless and will try to keep "popular" records up-to-date.

`serve-expired` can have unexpected consequences (e.g., #1175) based on configuration. If you want to still use it, I would use `serve-expired-client-timeout: 1800` so that expired records are only used as a fallback to recursion failures.
And then again you need to consider setting `serve-exprired-ttl`. However I don't have a value to suggest there as it all depends on individual records and everything is pretty hand-wavey. [The RFC suggests a value between 1 and 3 days](https://www.rfc-editor.org/rfc/rfc8767#section-5-11). You can find more information about the option in the manpage or [online for the latest version](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-serve-expired).

**Comment by Aura67** [comment]
OK, that's fine, this option isn't suitable for my Unbound, I prefer to use prefetch-key: yes, but thanks for the answer.
