### ISSUE TITLE
[FR] Ability to update RTT_BAND for server selection

### ISSUE THREAD

**Issue by shubhhq** [NLnetLabs/unbound#1203]
**Current behavior**
Today, The fastest server (randomly picked within a so-called RTT band of 400 msec) is selected when a query has to be sent out. The roundtrip-timeout (rtt) is used for selection purposes.

**Describe the desired feature**
Currently the value 400 msec is fixed and hardcoded, is there a possibility of making it configurable. I want 2 servers within 50msec to be treated same but not 400msec.

**Potential use-case**
Failover to geographically distant servers but only in case where nearer servers fail, the application is latency sensitive so every msec matters for us.

**Comment by bjovereinder** [comment]
Hi,

Have you had a look at the following options that could be used for your particular use case?

**fast-server-permil: <number>**
Specify how many times out of 1000 to pick from the set of fastest servers. 0 turns the feature off. A value of 900 would pick from the fastest servers 90 percent of the time, and would perform normal exploration of random servers for the remaining time. When [prefetch:](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-prefetch) is enabled (or [serve-expired:](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-serve-expired)), such prefetches are not sped up, because there is no one waiting for it, and it presents a good moment to perform server exploration. The [fast-server-num:](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-fast-server-num) option can be used to specify the size of the fastest servers set.
Default: 0

**fast-server-num: <number>**
Set the number of servers that should be used for fast server selection. Only use the fastest specified number of servers with the [fast-server-permil:](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-fast-server-permil) option, that turns this on or off.
Default: 3

**Comment by shubhhq** [comment]
Thanks for sharing this. 
Does this mean if I keep fast-server-permil as 1000 and fast-server-num as 1, it would 1) choose the single fastest server all the time and 2) fallback to slower servers when the faster server fails (this is very important) ?

**Comment by bjovereinder** [comment]
I would not suggest using 1000, but rather 990 (or 995,...) to probe the RTTs of other name servers, which may change and improve over time and become a better option and give a name server with higher preverence.  

For more background information on server selection see https://unbound.docs.nlnetlabs.nl/en/latest/reference/history/info-timeout-server-selection.html.
