### ISSUE TITLE
"make" encounter error

### ISSUE THREAD

**Issue by luckypoem** [NLnetLabs/unbound#139]
hi.

on my centos vps.
wget https://nlnetlabs.nl/downloads/unbound/unbound-1.9.2.tar.gz
tar xvf unbound-1.9.2.tar.gz
cd unbound-1.9.2
./configure --with-libevent
make 
it shows:

./libtool --tag=CC --mode=compile gcc -I.  -I/usr/local/include -I/usr/local/include -DSRCDIR=. -g -O2 -flto -pthread  -o val_secalgo.lo -c validator/val_secalgo.c
libtool: compile:  gcc -I. -I/usr/local/include -I/usr/local/include -DSRCDIR=. -g -O2 -flto -pthread -c validator/val_secalgo.c  -fPIC -DPIC -o .libs/val_secalgo.o
validator/val_secalgo.c: In function ‘setup_dsa_sig’:
validator/val_secalgo.c:329:8: error: dereferencing pointer to incomplete type
  dsasig->r = R;
        ^
validator/val_secalgo.c:330:8: error: dereferencing pointer to incomplete type
  dsasig->s = S;
        ^
validator/val_secalgo.c: In function ‘setup_key_digest’:
validator/val_secalgo.c:473:17: warning: assignment makes pointer from integer without a cast [enabled by default]
    *digest_type = EVP_dss1();
                 ^
validator/val_secalgo.c: In function ‘verify_canonrrset’:
validator/val_secalgo.c:695:35: error: dereferencing pointer to incomplete type
  ctx = (EVP_MD_CTX*)malloc(sizeof(*ctx));
                                   ^
make: *** [val_secalgo.lo] Error 1

how to fix it?

**Comment by wcawijngaards** [comment]
Hi,
It looks like Unbound is calling the wrong part of the openssl API.  This changed in openssl new versions.  Unbound detects what it should do in the configure step.

Older versions of unbound did not check this and also had this kind of failure.  Just upgrade to fix that.

But if the error is still there, then, perhaps, you have more than one version of openssl installed and it uses a different versoin of openssl during configure and during the compile?

Best regards, Wouter

**Comment by luckypoem** [comment]
@wcawijngaards 
i think u are right.
i bought another new vps,and i compile unbound in the new vps successfully as follows:
wget https://nlnetlabs.nl/downloads/unbound/unbound-1.9.6.tar.gz
tar xvf unbound-1.9.6.tar.gz
cd unbound-1.9.6
./configure --enable-subnet --with-libevent --with-ssl
make && make install

i rememered vaguely i seem to upgrade the openssl in my first vps,but how to use the correct openssl version during configure and during the compile in my first vps?

**Comment by wcawijngaards** [comment]
Hi,

Good to see you can make it work.

If you want to use multiple versions of openssl, you would need different directories to put them in.  This gets awkward because the system insists on putting one of them in the system library directory.  You would need to set up directories with the libraries at the versions that you want them to be and use --with-ssl=/directory option, like --with-ssl=/home/myuser/libraries/openssl  (with lib/ and include/ directories in there).  You can make that by compiling openssl and making in install to that /home/myuser/libraries/openssl directory as the install prefix (instead of /usr).  With files spread around it can get awkward, unbound can set the directory you want with --with-ssl=/usr/local or /opt/local or something like that, but ultimately it is a set of -I and -L flags to the compiler.

It is also possible that you simply installed the lib but not the include part of openssl in /usr/local/include.  If so, update that to match the openssl version (with the openlssl-dev package or so).

So, to repeat that, the compile environment must be wrong somehow; setting it straight or giving some --with-ssl=/somedir option to point the compiler in a better direction seems to be it.  It can be even worse (for other people perhaps), when they have a wrong version of openssl in /usr/local, and want to use the /usr one, but then have /usr/local for another library, like libexpat or libevent.  And then the compiler cannot figure it out.  To solve that sort of thing, have separate directories with only one library installed in them; one for libevent, one for libexpat, one for openssl, this works for me in development to link with arbitrary libraries on a Linux system.  Just pass the directories (as appropriate) to the configure commandline.

Best regards, Wouter

**Comment by luckypoem** [comment]
hi.

mv /usr/bin/openssl /usr/bin/openssl.bak
mv /usr/include/openssl /usr/include/openssl.bak
mv /usr/lib64/openssl/ /usr/lib64/openssl.bak
rm -rf /usr/loca/include/openssl/

then,
wget https://www.openssl.org/source/openssl-1.1.1a.tar.gz
tar xvf openssl-1.1.1a.tar.gz
cd openssl-1.1.1a
ls /root/openssl-1.1.1a/.openssl/
bin  include  lib

cd ~
wget https://nlnetlabs.nl/downloads/unbound/unbound-1.9.2.tar.gz
tar xvf unbound-1.9.2.tar.gz
cd unbound-1.9.2
./configure --enable-subnet --with-libevent —with-ssl=/root/openssl-1.1.1a/.openssl/
make
make install
(then unbound is compiled successfully)

rm -rf /usr/local/bin/openssl
ln -s /root/openssl-1.1.1a/.openssl/bin/openssl /usr/local/bin/openssl

then my issue is fixed.
tks a lot

**Comment by luckypoem** [comment]
@wcawijngaards 
i saw your team jointly develop stubby.i have a question:
in this command：echo | openssl s_client -connect 'mydomain.com:853' 2> /dev/null | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64

do i need to replace the pubkey and pkey with the certificate file and private key file downloaded from my vps?

**Comment by wtoorop** [comment]
Hi @luckypoem ,
Is your intention to create a pin for the certificate for your own DoT unbound resolver? From the certificate file? When the certificate file is called `cert.pem`, you can do that with:
```
openssl x509 -in cert.pem -noout -pubkey | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
```

**Comment by luckypoem** [comment]
@wtoorop 

i setup my own DoT unbound resolver.i use other client to connect to it successfully.but i use stubby to connect to it, failed:

yudeMacBook-Air:stubby brite$ stubby -C stubby-from-bwg.yml
Could not configure context with config dict: The library did not have the requested API feature implemented.
Could not parse config file "stubby-from-bwg.yml": The library did not have the requested API feature implemented.
yudeMacBook-Air:stubby brite$ cat stubby-from-bwg.yml
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 256
edns_client_subnet_private : 0
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1
  -  0::1
round_robin_upstreams: 1
upstream_recursive_servers:
  - address_data: my-vps-ip
tls_auth_name: "mydomain.com"
tls_pubkey_pinset:
- digest: "sha256"
value: qrKm+EpaRQwotQGxk1qPQtvD2pHsnmdsZIDXDDEZLI4=

i don't know why i failed.is stubby-from-bwg.yml not correct?
how to fix it?

**Comment by wtoorop** [comment]
Hi @luckypoem from the surface this looks just fine to me, but stubby is quite sensitive to the way things are expressed, so just to be sure, could you try the stubby config file attached hereby: [stubby-from-bwg.yml.gz](https://github.com/NLnetLabs/unbound/files/4040506/stubby-from-bwg.yml.gz)

And see if that works, and if it works replace the getdnsapi.net values with yours?
Thanks!

**Comment by luckypoem** [comment]
it does work.
thank u so much.
@wtoorop
