### ISSUE TITLE
cache confusion results in NXDOMAIN for existing names

### ISSUE THREAD

**Issue by gbon121** [NLnetLabs/unbound#162]
This issue was found in version 1.9.0 running on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950714

Sometimes unbound replies to a query for a forward-zone using a spurious
cache entry, resulting in bogus NXDOMAIN responses that persist for
cache-max-negative-ttl seconds (1 hour, by default), effectively
disrupting name resolution for the zone.

Given this piece of configuration on 10.0.2.15:

    server:
        do-ip6: no
        interface: 127.0.0.1
        log-queries: yes
        log-replies: yes
        log-servfail: yes
        log-tag-queryreply: yes
        statistics-cumulative: yes
        statistics-interval: 3607
        val-log-level: 2
        verbosity: 4
        logfile: /var/log/unbound.log

        domain-insecure: test.local

    forward-zone:
        name: test.local
        forward-addr: 10.0.2.2

and the zone test.local defined on 10.0.2.2 like this: 

    $TTL 3600    ; 1 hour
    @    SOA     x.test.local. root.test.local. (
                 1          ; serial
                 900        ; refresh (15 +minutes)
                 600        ; retry (10 minutes)
                 86400      ; expire (1 day)
                 3600       ; minimum / negative ttl (1 hour)
         )
         NS      x.test.local.
    x    A       10.0.2.2
    y    A       10.0.2.10

responses from a freshly started instance of unbound on 10.0.2.15 depend on
query ordering:

successful sequence:

    # service unbound restart
    # dig @127.0.0.1 A y.test.local.      => 10.0.2.10 (correct)
    # dig @127.0.0.1 A nonexistent.local. => nxdomain  (correct)
    # dig @127.0.0.1 A y.test.local.      => 10.0.2.10 (correct)

failing sequence:

    # service unbound restart
    # dig @127.0.0.1 A nonexistent.local. => nxdomain  (correct)
    # dig @127.0.0.1 A y.test.local.      => nxdomain  (WRONG)

    
At verbosity 4, the logfile contains this excerpt:

    [1580891316] unbound[1842:0] info: msg from cache lookup
    ;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 0
    ;; flags: qr ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 6, ADDITIONAL: 0 
    ;; QUESTION SECTION:
    y.test.local.   IN      A

    ;; ANSWER SECTION:

    ;; AUTHORITY SECTION:
    loans.  86394   IN      NSEC    locker. NS DS RRSIG NSEC
    loans.  86394   IN      RRSIG   NSEC 8 1 86400 20200217170000 [...]
    .       86394   IN      NSEC    aaa. NS SOA RRSIG NSEC DNSKEY
    .       86394   IN      RRSIG   NSEC 8 0 86400 20200217170000 [...]
    .       3594    IN      SOA     a.root-servers.net. nstld.verisign-grs.com.
                                    2020020401 1800 900 604800 86400
    .       86394   IN      RRSIG   SOA 8 0 86400 20200217170000 [...]

    ;; ADDITIONAL SECTION:
    ;; MSG SIZE  rcvd: 1022

That entry looks like a response packet with rcode NXDOMAIN and Question
"y.test.local. IN A".

The network capture, however, shows that no such reply was ever received by
unbound.  In fact unbound sent no query for "y.test.local." or "test.local."
to 10.0.2.2 or root nameservers.

The closest match is the packet received from a root server with rcode
NXDOMAIN and Question "local. IN A".  Looks like the above "msg from
cache" is spurious.

**Comment by wcawijngaards** [comment]
Hi,
You mean stub-zone instead of forward-zone, because it sends the packets to an authoritative server.  I do not think that fixes it, but it is wrong in your configuration.

So, the name local is not in the stub-zone and thus answered from the internet, where it is NXDOMAIN.  That answer is expanded to include all names below it, because we have nxdomain hardening on by default.  This is the option `harden-below-nxdomain: yes` if you turn if off, likely that would stop your problem.

The actual problem is that the label ".local" itself does not have a proper answer.  And it has to be answered with noerror/nodata answers, or just an A record or TXT record to put something there. One way would be to make a stub-zone for name: "local" and send it to the same authority as test.local. Even if it does not answer, that should prevent the NXDOMAIN from the public internet from getting used there.  Another option would be to create a small authority for only the .local name, and have a stub-zone for that.  It has an (mostly empty) zonefile for .local.

**Comment by wcawijngaards** [comment]
I mean, likely your problems can go away with either the option `harden-below-nxdomain: no` or if you change the name of the forward-zone you have to `name: "local"` in the config file (you do not have to change its zonefile).    And also make that a `stub-zone:` because it sends to an authority server.

**Comment by gbon121** [comment]
Thanks, Wouter.  Both your suggestions (disable `harden-below-nxdomain`, or forward all "local." instead of just "test.local.") solve the problem.

Yet the log mentions a cached message with Q=y.test.local. and A=nxdomain, that is not there.  Had it read "Q=local. and A=nxdomain", the effect of the "nxdomain cut" would have been evident (although unexpected).

The logic of your second solution (forward all "local"), eludes me.  It results in this sequence:
`dig  @127.0.0.1 A local.` *nxdomain*
`dig  @127.0.0.1 A nonexistent.local.`  *nxdomain*
`dig  @127.0.0.1 A y.test.local.` *10.0.2.10*
Per the "nxdomain cut", shouldn't the first query prevent the last from succeeding?

BTW, test.local is a forward-zone instead of a stub-zone because 10.0.2.2 is authoritative for the zone only by accident, just in this minimal test scenario.  In real life, there's a recursor in its place and I'm not allowed to query the auth servers.

**Comment by wcawijngaards** [comment]
Also `domain-insecure: "local"` may solve the problem as well. It makes the nxdomain insecure for local stopping the harden for nxdomain from picking it up.

Yes the log talks about the synthesized message.  Unbound uses cached elements from previous traffic to create that response.

The logic for the second response is that it puts all the info in the forward-zone, the iterator can see that there is a forward-zone with that specific label and thus move to get the data from there.

**Comment by gbon121** [comment]
This third solution (`domain-insecure: local` combined with `forward-zone: name: test.local`) doesn't work, at least in version 1.9.0.
