### ISSUE TITLE
Capsforid timeout leads to "equal-replies-requirement", which is a really bad idea

### ISSUE THREAD

**Issue by tik-stbuehler** [NLnetLabs/unbound#213]
The setup:
- multiple NS for `example.com`, the same for `foo.example.com`, and a subset for `bar.foo.example.com`
- one of the NS (for `example.com`) is down.
- the one down is tried first (no idea for which query) -> `Capsforid: timeouts`
- now suddenly unbound expects equal replies from all other NS; but that can't work: some of those will delegate, others can actually answer

```
Apr 02 09:18:44 unbound[16991:0] info: Capsforid: timeouts, starting fallback
Apr 02 09:18:46 unbound[16991:0] info: Capsforid: reply is equal. go to next fallback
Apr 02 09:18:46 unbound[16991:0] info: Capsforid: reply is equal. go to next fallback
Apr 02 09:18:46 unbound[16991:0] info: Capsforid fallback: getting different replies, failed
```

And now letsencrypt fails.

WTF?

See: https://unboundtest.com/m/CAA/cloud.pi5.physik.uni-stuttgart.de/PISNQN4V
Copy of the log: [CAA_cloud.pi5.physik.uni-stuttgart.de_unbound.txt](https://github.com/NLnetLabs/unbound/files/4426285/CAA_cloud.pi5.physik.uni-stuttgart.de_unbound.txt)

**Comment by ralphdolmans** [comment]
The resolving failure here is the result of a mix of corner cases that are triggered for this domain.

Because there are nameservers in the wild that do not give an answer to 0x20 queries Unbound has a fallback available in an attempt to make it work anyway. This fallback indeed tries to match different responses. This usually works, but not always, think CDN cases. The assumption here is that trying the fallback is better than not doing anything at all because that means a resolution failure right away.

There is no easy way to distinguish between a timeout because of the 0x20 queries, or for another reason. Unbound therefore does not start the fallback right away after a timeout, but does (or should) do so after a couple of failed queries. This is implemented by checking the number of queries that are send out for a delegation point.

Unbound has a check to query another nameserver when the answer is expected to contain DNSSEC signatures, but does not. In your case `uni-stuttgart.de.` has a DS record, when sending queries to the nameservers for that domain Unbound therefore expects to get DNSSEC signatures. Because the *unsigned* `physik.uni-stuttgart.de.` is answered from the same nameservers this answer does not contain DNSSEC signatures, causing Unbound to mark it as DNSSEC lame and tries to find a better answer. Unbound is aware of this corner case and is able to successfully get an answer here, but does send out more queries for the same name. In your case, even though only one nameserver is unreachable (131.246.119.18) the capsforid fallback is still started because of the combination of a timeout and exceeding the query count threshold.

I made some changes to the Unbound code to keep track of the number of timeouts, and use that to determine if the capsforid fallback should be started. See https://github.com/NLnetLabs/unbound/commit/03a37d1ff6744308493bfa5c20dc2dd2f2522022. This will result in Unbound being able to get an answer for your domain.

So that is the reason why the fallback exists and when it will be started. In your case, the fallback fails because you do something weird. The zonecuts in your domain are different for different nameservers. I discourage you to do so as this will lead to strange behavior. Resolvers will for example cache the most specific delegation point, potentially resulting in unexpected traffic patterns. Signing your zones with DNSSEC will also be problematic.
