### ISSUE TITLE
unbound-control and self-signed cert

### ISSUE THREAD

**Issue by vollkommenheit** [NLnetLabs/unbound#218]
This is a hybrid issue / possible feature request.

I have no issue using unbound-control 1.10.1 (nightly build, built against OpenSSL-1.1.1g) on a LAN host with the localhost unbound daemon 1.10.1. However, from the same LAN host, when I try to manipulate the unbound 1.10.0.2 server on my router, I keep getting: 

> error: SSL handshake failed
140735231270912:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915:

`# openssl s_client -connect ${router_ip}:8953 -statutus`
initially returned
> Verify return code: 18 (self signed certificate)

I have added the router's "unbound_server.pem" to the LAN host's $OPENSSLDIR/certs by following the guide at ( http://gagravarr.org/writing/openssl-certs/others.shtml#selfsigned-openssl ). This appears to satisfy OpenSSL on the LAN host, because

`# openssl verify -CApath $OPENSSLDIR/certs $OPENSSLDIR/certs/unbound_control.pem`
returns
> OK

Further, both
`# openssl s_client -connect ${router_ip}:8953 -CApath /usr/local/ssl/certs`
and 
`# openssl s_client -connect ${router_ip}:8953 -status`
now return
> Verify return code: 0 (ok)
...
instead of the previous:
...
> Verify return code: 18 (self signed certificate)

I have appended the "unbound_server.pem" and "unbound_control.pem" of both the router and the LAN host to each other's respective counterpart.

I have appended the "unbound_server.pem" of both the router and the LAN host to each other's /etc/unbound/ca-certificates.crt (as in unbound.conf's "tls-cert-bundle: /etc/unbound/ca-certificates.crt"), though it may not serve this purpose of mine.

However, I'm still getting the above "error: SSL handshake failed ... certificate verify failed" when using unbound-control from the LAN host to the router.

So, either I'm still missing something, or maybe unbound-control could optionally accept a flag to specifically ignore "certificate verify failed" or SSL error type 18 regarding self-signed cert from CA "unbound" / CN=unbound-control, similar to wget's --no-check-certificate?

**Comment by wcawijngaards** [comment]
Hi,
If you want unbound to ignore the certificate, simply do not give a tls-cert-bundle, as in "", and do not specify a host auth name to check for in the config of the tls destination.

That said, unbound should just use the list of certs that you give it, and that should work, eg. adding it to the list of certs loaded by tls-cert-bundle.  There is even a unit test that uses `tls-cert-bundle: unbound_server.pem` and that works.  Is the second 'certificate verify failed' because of another reason, i.e you solved the CA not there problem, but it has another problem when you try later, what was the detailed message?

**Comment by wcawijngaards** [comment]
Wait, spotted this a bit later: are you try to use TLS for DNS connections, with tls-cert-bundle, but it looks like really, you may be trying to use unbound-control to connect to the remote-control port?  That is governed by the options in the remote-control section.  It does not use that cert bundle, so that makes no difference.

**Comment by wcawijngaards** [comment]
If you are trying to simple connect with unbound-control to unbound running on another computer.  What that needs is that you set remote-control control-enable: yes and control-interface: to an accessible interface (not 127.0.0.1).  And then copy the .key and .pem files to the other machine, and use unbound-control -c someconfig.conf where that config contains a remote-control section with the destination IP-address, and the locations of the copied .key and .pem files.  (The client does not need the server private key file, but you need to copy the other three files for it).

**Comment by vollkommenheit** [comment]
Thanks for your replies. Yes, my issue is regarding intra-LAN unbound-control; I'm set on TLS for DNS connections using tls-cert-bundle (but I learned something new here too, like the empty "" to not check cert). 

I will copy over the three files (unbound_control.pem, unbound_control.key, and unbound_server.pem) and report back how it goes.

**Comment by vollkommenheit** [comment]
So I copied the router's entire /etc/unbound/* to the LAN host's newly created /etc/unbound/router/ directory. The router's unbound.conf ( /etc/unbound/router/unbound.conf on the LAN host ) has the following:

> remote-control:
  control-enable: yes
  control-use-cert: yes
  control-interface: 127.0.0.1
  control-interface: ::1
  control-interface: 10.0.0.1
  server-key-file: "unbound_server.key"
  server-cert-file: "unbound_server.pem"
  control-key-file: "unbound_control.key"
  control-cert-file: "unbound_control.pem"

Then from LAN host to the router:
`# unbound-control -s 10.0.0.1 status -c /etc/unbound/router/unbound.conf`
I still get:
> error: SSL handshake failed
140735231270912:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915:

In router syslog:
> Apr 14 23:48:50 unbound[21022:0] error: remote control failed ssl crypto error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca

I have added the LAN host unbound's unbound_server.pem to the router's OpenSSL (and vice versa, as reported in the first post), verified on the router as below:
`openssl verify -CApath /etc/ssl/certs /etc/ssl/certs/unbound_control.pem`
> /etc/ssl/certs/unbound_control.pem: OK

where /etc/ssl/certs/unbound_control.pem is copied from the LAN host's unbound 1.10.1, not the router's own.

So the router's OpenSSL is definitely aware of the LAN host's CA=unbound

What am I still missing?

Also, I noticed "control-use-cert: yes" and tried to see if it might work without using cert, i.e.:
remote-control:
  ...
  control-use-cert: no

`# unbound-control -s 10.0.0.1 status -c /etc/unbound/router/unbound.conf`
I simply get:
> error: SSL handshake failed

And nothing in router's syslog

**Comment by vollkommenheit** [comment]
Never mind. Just got it working now. 

First, it seems "-c /etc/unbound/router/unbound.conf" must be the first argument after unbound-control:
` # unbound-control -c /etc/unbound/router/unbound.conf -s 10.0.0.1 status`
rather than 
` # unbound-control -s 10.0.0.1 status -c /etc/unbound/router/unbound.conf `

Second, since the router's unbound.conf gets transplanted to the LAN host as /etc/unbound/router/unbound.conf, EITHER the four lines of key and pem file directives must be updated to reflect the new full path on the LAN host (OR otherwise in the "server: " section, update "directory: /etc/unbound" to the new path "directory: /etc/unbound/router".)

> remote-control:
control-enable: yes
control-use-cert: yes
control-interface: 127.0.0.1
control-interface: ::1
control-interface: 10.0.0.1
server-key-file: "/etc/unbound/router/unbound_server.key"
server-cert-file: "/etc/unbound/router/unbound_server.pem"
control-key-file: "/etc/unbound/router/unbound_control.key"
control-cert-file: "/etc/unbound/router/unbound_control.pem"

Thanks for all the advice.

**Comment by wcawijngaards** [comment]
Good that you made it work!  I'll try to explain some things that happened:

The -c argument has to be first, this is because FreeBSD (or *BSD) getopt option parsing does that.  On Linux, the glibc getopt option parsing allows different argument order, and you could put the '-c' after the positional arguments.

For the -s 10.0.0.1 needed, if the config file has only one control-interface, and that is 10.0.0.1, then it would work from that and not need a commandline argument for unbound-control.  (That config file would then not be the one for the running unbound daemon on that machine, but a config file you use to contact a remote one, I guess).  Just use the commandline argument to set it if that is easier.

The use-cert option is for people that use a unix pipeline (a filename in the control-interface) for unbound-control communication.  That would only work on the local machine of course.

You keep adding the server certificate to the general openssl cert directory in /etc, but the unbound-control does not use it.  It only uses the files listed in the remote-control section.  So when you copied those and fixed the pathnames, it worked (that is what it looks like).

**Comment by vollkommenheit** [comment]
Thanks for the edification.

You're spot on: my LAN host is a BSD-like system, and I was scratching my head over the need to make "-c unbound.conf" the first arg, because I saw posters on the unbound listserv putting it at the end just fine. Now, obviously they were on Linux.

I'm wondering: Is there a specific reason, if any at all, that "unbound-control -s" only takes an IP addr, rather than also optionally accepting locally or publicly resolvable hostnames such as "router.local" / "mydomain.net"? 

Also, since we touched on the subject in passing, I had 
`forward-tls-upstream: yes` configured
but, I was not aware of 
`tls-cert-bundle: ca-certificates.crt`
Then I read a blog that mentions that using 
`forward-tls-upstream: yes` without `tls-cert-bundle` leaves unbound susceptible to DNS MITM attacks. 
I'm wondering: Does that combo 
`forward-tls-upstream: yes` without ~~`tls-cert-bundle: ca-certificates.crt`~~
have the exact same less-than-desirable effect as 
`forward-tls-upstream: yes` + `tls-cert-bundle: ""` (not specifying a cert file)?

**Comment by wcawijngaards** [comment]
For that -s with an IP address, because name resolution uses the DNS and this creates a circular dependency that you are better off without, eg. control of the nameserver does not depend on the DNS working.  Otherwise it is also easier, but if I wanted to implement and be good about it that would mean a full resolver in unbound-control commandline tool to fetch that name, eg. entirety of unbound...

The tls-cert-bundle unspecified:  That is about the default value of the tls-cert-bundle config option.  And that is currently "" and 'no' for the windows cert store.  So you are right.  To set that by default we'd need a configure option and something sensible to set it to.
