### ISSUE TITLE
DNS fails to resolve for a particular TLD

### ISSUE THREAD

**Issue by praneeth101** [NLnetLabs/unbound#235]
Hello,

I'm running Unbound as a recursive DNS server for Pi-Hole. I've run into a peculiar problem recently, DNS queries timeout for a particular TLD, which is: `.trade`
Queries for all other TLDs work perfectly. 

```
pi@raspberrypi:~ $ dig kite.trade @127.0.0.1 -p 5353

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> kite.trade @127.0.0.1 -p 5353
;; global options: +cmd
;; connection timed out; no servers could be reached
pi@raspberrypi:~ $ dig tech.trade @127.0.0.1 -p 5353

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> tech.trade @127.0.0.1 -p 5353
;; global options: +cmd
;; connection timed out; no servers could be reached
pi@raspberrypi:~ $ dig google.com @127.0.0.1 -p 5353

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> google.com @127.0.0.1 -p 5353
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5926
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             300     IN      A       216.58.200.142

;; Query time: 62 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Mon May 11 02:26:38 BST 2020
;; MSG SIZE  rcvd: 55
```
Unbound log on verbosity 3: https://pastebin.com/RzA3VmAT

I have an identical Pi-Hole/Unbound setup on a VPS and that works as expected. 

To rule out ISP blocking requests to certain IPs, when I query the name servers for the TLD (from here: https://www.iana.org/domains/root/db/trade.html), it works:

```
pi@raspberrypi:~ $ dig kite.trade @156.154.158.165

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> kite.trade @156.154.158.165
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37468
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kite.trade.                    IN      A

;; AUTHORITY SECTION:
KITE.trade.             7200    IN      NS      KEN.NS.CLOUDFLARE.COM.
KITE.trade.             7200    IN      NS      KARA.NS.CLOUDFLARE.COM.

;; Query time: 159 msec
;; SERVER: 156.154.158.165#53(156.154.158.165)
;; WHEN: Mon May 11 02:29:10 BST 2020
;; MSG SIZE  rcvd: 98
```

**Comment by wcawijngaards** [comment]
Can you create a debug log with verbosity 4?  It looks like that could contain more details.  I see the trade DS record mentioned twice in your verbosity 3 logs, and I am not sure, but that could be a DNSSEC validation issue.  If you enable val-log-level: 2  and perhaps also log-servfail: yes  then unbound can create convenient short log messages informing you what happened.

**Comment by praneeth101** [comment]
A log with:
```
verbosity: 4
val-log-level: 2
log-servfail: yes
```
https://pastebin.com/VTcdxB5S

Thank you for taking the time to check this out.

**Comment by wcawijngaards** [comment]
From these logs it shows that the .trade nameservers are not responding to queries.  None return.  In the first post you show that it responds to a dig.  But queries sent by unbound are unanswered.

`dig @156.154.158.165 trade DNSKEY +cdflag +dnssec` is one way to do it, and this enabled CD and dnssec DO flags, perhaps that is the difference.  But still weird for them to drop the queries, perhaps they are ratelimiting (your network neighborhood?).

If I do that query, I get no response either.   The nameserver for .trade seems to not respond to DNSSEC queries for DNSKEY.  The query for kite.trade `dig @156.154.158.165 kite.trade A +cdflag +dnssec` gets an answer for me.  The kara.ns.cloudflare server also responds and kite.trade A can be resolved.

The .trade nameservers timeout to DNSKEY queries.  Yes that would stop unbound from resolving the content.  You could either fix that, eg. by fixing the .trade nameserver or a firewall that drops queries for .trade DNSKEY or so.  Or set domain-insecure: "trade"

For me the .trade DNSKEY response works over TCP (with +tcp).  Some sort of response size issue, that is likely then very close to the .trade nameserver, if it happens for me and you.  I mean a middlebox or firewall drops fragmented responses that the nameserver creates in response to the DNSKEY query.  That middlebox, since it happens for me and you, is then likely not over where we are, but over where the nameserver is, or, on the way to that nameserver.   I see the DNSKEY query succeed with +bufsize=1480 that inhibits the fragment creation.  Unbound has options to control this behaviour, but they should already default to this, I thought.

The unbound, latest version, here, tries a smaller EDNS bufsize for that .trade DNSKEY lookup and that succeeds the lookup.  Perhaps you could upgrade to get this behaviour too.  edns-buffer-size: 1472 can solve the fragmentation issue (also without an upgrade), by advertising a smaller buffer size and thus avoiding the fragmentation.

**Comment by praneeth101** [comment]
When I do `dig @156.154.158.165 trade DNSKEY +cdflag +dnssec` it works (I get the NOERROR status and a bunch of DNSKEY entries). 
My configuration already has `edns-buffer-size: 1472`.  I have an identical Pi-Hole/Unbound setup on a VPS (same version and config) and that works without problems. This probably confirms that it could be an issue with a middlebox or firewall, like you suggested. 
Setting `domain-insecure: "trade"` fixed the problem!

**Comment by beatquantum** [comment]
I had the same problem with the "cloud" TLD and I used a temporary fix
server:
  domain-insecure: "cloud"

Also used 
unbound-checkconfig
systemctl restart unbound
systemctl status unbound
dig A <domainname>.cloud
