### ISSUE TITLE
[feature suggestion | auth-zone] provide option to retain zone file only on disk and offload from RAM

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#236]
>Version 1.10.0

>Configure line: --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-dsa --disable-gost --enable-allsymbols --enable-subnet --with-libexpat=/home/beast/beast/workspace/turris-os-packages-lions-omnia/build/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --with-ssl=/home/beast/beast/workspace/turris-os-packages-lions-omnia/build/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --without-pthreads --enable-tfo-server --enable-tfo-client
Linked libs: pluggable-event internal (it uses select), OpenSSL 1.1.1g  21 Apr 2020
Linked modules: dns64 subnetcache respip validator iterator
TCP Fastopen feature available
____
with `zonefile:` specified in `auth-zone:` I had hoped that the zone file would not reside in memory and *unbound* just accessing the zone file on the disk but apparently that is not the case.
On a node with a relatively small amount of RAM *unbound*'s memory footprint thus could easily lead to scarcity of available RAM with large zone files, e.g. some TLDs permit transfers like https://zonedata.iis.se

**Comment by gthess** [comment]
I am not sure I understand the problem :)
If you use `auth-zone:` then unbound will parse and load that zone (either from XFR or local file) into memory in order to serve/lookup data for that zone. If the auth-zone you are trying to use is a TLD you need the corresponding resources in order to serve/use that data.

`zonefile:` is only used to indicate a file containing initial zone data and/or where to dump zone data after a zone is updated.

Is your suggestion to not have a memory structure but instead always read from file when looking into auth zones?

**Comment by ghost** [comment]
> Is your suggestion to not have a memory structure but instead always read from file when looking into auth zones?

Yes, as option/alternative to loading large zone files into memory, if that would not tank the performance

**Comment by gthess** [comment]
That would tank performance and complicate things significantly if trying to do it _somewhat_ right.

It is not a trivial read from file to find a DNS answer in the auth-zone. The DNS tree needs to be constructed in order to reply for less trivial records like wildcards and proof of non-existence. Reading from file for each request and creating the tree would tank performance and spike memory usage while doing so.

You could argue that most visited records would slowly be cached but auth-zone answers are before the cache stage as auth-zone configuration may direct unbound to not use the auth-zone data for upstream queries, and we don't want those records in the cache then.

I cannot think of a solution that would still be performant and that would require the minimum amount of memory footprint. In all cases complexity greatly overcomes performance.

**Comment by ghost** [comment]
Thanks for the consideration and feedback. Probably need to upgrade the hardware, depending whether more TLDs opening up for zone transfers such as the folks in Sweden. Or if you find a way to lower the footprint for the tree structure in RAM :stuck_out_tongue_winking_eye:

**Comment by gthess** [comment]
Out of curiosity, what is your use case for serving TLDs from your resolver? Latency, research?

**Comment by ghost** [comment]
Same intention as for _. | arpa. | in-addr.arpa. | ip6.arpa._:

* enhance privacy for the local peers
* mitigate load on upstream resolvers
* decrease latency for the local peers
* lower bandwidth (though I am not sure whether the zone transfers may not actually increase bandwidth vs. individual queries considering that the TLDs are rather large in volume)

**Comment by ghost** [comment]
One thought, not sure whether practical/feasible - if *unbound* could opt to place the zone's DNS tree on swap space instead (if such is installed on the node), that would leave the DNS tree structure in place and free memory.
