### ISSUE TITLE
unbound[513:0] error: can't bind socket: Address already in use for 127.0.0.1 port 8953

### ISSUE THREAD

**Issue by Potterli20** [NLnetLabs/unbound#252]
He's got 8953? But I didn't move anything.

~# lsof -i:8953
COMMAND PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
unbound 508 unbound    5u  IPv4  17444      0t0  TCP localhost:8953 (LISTEN)
~# unbound
[1592494228] unbound[513:0] warning: so-rcvbuf 1048576 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
[1592494228] unbound[513:0] error: can't bind socket: Address already in use for 127.0.0.1 port 8953
[1592494228] unbound[513:0] error: cannot open control interface 127.0.0.1 8953
[1592494228] unbound[513:0] fatal error: could not open ports

**Comment by wcawijngaards** [comment]
Unbound connects, by default to that port for the remote-control functionality.  This is used by unbound-control to control the server from the commandline.  It can be changed if you want with the config statement `control-port: 1234` in the `remote-control` section of `unbound.conf`.

Unbound can also use named sockets for communication with unbound-control.  To set that up you need a file that is going to be accessible for the commandline user (with permissions) and then you set a control-interface for the absolute path to that file.  You can also change the control-interface to an ip-address if you want the unbound-control to be accessible (with TLS) over the network, but by default it is only for localhost.  So for example with `control-interface: "/var/run/unbound-control.sock"` that would use the named socket, and then unbound-control connects to that file pipe to communicate with the server.  Since it then uses a named file and not the network, it would not use that port.

For ease of reference, here is a link to the documentation for the options:
https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/#control-interface
https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/#control-port

**Comment by Potterli20** [comment]
> Unbound connects, by default to that port for the remote-control functionality. This is used by unbound-control to control the server from the commandline. It can be changed if you want with the config statement `control-port: 1234` in the `remote-control` section of `unbound.conf`.
> 
> Unbound can also use named sockets for communication with unbound-control. To set that up you need a file that is going to be accessible for the commandline user (with permissions) and then you set a control-interface for the absolute path to that file. You can also change the control-interface to an ip-address if you want the unbound-control to be accessible (with TLS) over the network, but by default it is only for localhost. So for example with `control-interface: "/var/run/unbound-control.sock"` that would use the named socket, and then unbound-control connects to that file pipe to communicate with the server. Since it then uses a named file and not the network, it would not use that port.
> 
> For ease of reference, here is a link to the documentation for the options:
> https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/#control-interface
> https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/#control-port

But I don't want to use it.

**Comment by wcawijngaards** [comment]
The remote control functionality is disabled by default, it must have been enabled by config files shipped with the package you are using.  Which is sensible because many people want this functionality to work out of the box.  The option to turn it off is `control-enable: no` in the `remote-control` section of `unbound.conf`.
https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/#control-enable

If you turn that off, unbound should not open that port number.

**Comment by Potterli20** [comment]
> The remote control functionality is disabled by default, it must have been enabled by config files shipped with the package you are using. Which is sensible because many people want this functionality to work out of the box. The option to turn it off is `control-enable: no` in the `remote-control` section of `unbound.conf`.
> https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/#control-enable
> 
> If you turn that off, unbound should not open that port number.

I still have it when I close it, it still shows the port when I open it, and it doesn't say 8953 on my configuration file.

**Comment by wcawijngaards** [comment]
Close what? Open what?  You mean the server stop and start? If you stop the server it still uses a port number?  Did you manage to make configuration edits?

The port number is the default for the port number.  Hence it may not appear in your config file, and be used.  But you have nondefaults in your config because control-enable is yes.  In other cases people report editing the wrong file, eg. they have several because multiple instances or choice mechanisms move the files around.
