### ISSUE TITLE
memory leak in unbound

### ISSUE THREAD

**Issue by pmazzini** [NLnetLabs/unbound#256]
I am opening this issue to track the bug described in:
https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=4220

We still see this on unbound 1.9.6.

**Comment by wcawijngaards** [comment]
This may be a sillly question this far into the conversation, but it occurs to me and I do not see it (quickly) as asked before. Do you have a very high number for the infra cache size.  And it simply fills up?  One explanation would be that a reload causes re-lookups of the information, what with the rrset cache empty but the infra cache item still in existence for the nameservers, unbound performs lookups of the nameservers, and creates a new rrset entry for them.  And a new infra cache item, roughly doubling the memory in use by the re-looked up names, in the infra cache.  The lookups are random what nameserver name is looked up.  Thus it could randomly pick another set of names after the reload.  And it then creates infra items for them.

What you could do is simply lower the number of `infra-cache-numhosts` in unbound.conf, it is 10000 by default. That would be 10000 entries of a bunch of bytes each, if that was 1Kb (probably less than that) it would be 10M memory.  If you set that to 10000000, it would grow up the 10G or a bunch of Gbs.

Looking at this again after a while has benefits of a new approach.  If you are very interested in ECS, note there is a CNAME related fix for ECS upcoming for upcoming releases that you likely want.  (It fixes the scope for the cached ECS CNAME answer).

**Comment by wcawijngaards** [comment]
I can suggest a value for you, since earlier you noted something like 200 - 400 Mb for the infra cache memory use was fine; so a suggested `infra-cache-numhosts: 400000` could keep it there.

**Comment by leoleovich** [comment]
@wcawijngaards thanks for your quick replies! Currently our `infra-cache-numhosts` is set to `1000000` (1M) just 2.5 times your suggestion. According to calculations you provided it should not be more than 100MiB, but we see an increase sometimes >1GiB.

I am attaching the graph illustrating multiple completely equal hosts where 1 of them (green) got `flush_infra` hack removed. As you can see leak progresses rapidly and seems indefinite. When we add the hack again the RSS is back to "normal".

![Screenshot 2020-06-29 at 11 43 34](https://user-images.githubusercontent.com/4749052/85997246-30855700-ba01-11ea-8a86-c25912db7b7b.png)

**Comment by wcawijngaards** [comment]
What is on the vertical axis of that graph?

**Comment by leoleovich** [comment]
Bytes of Rss. So in this case it's up to 17 GiB.

**Comment by wcawijngaards** [comment]
Yeah, it is not that config item with that much memory involved.

**Comment by wcawijngaards** [comment]
Because I also don't have really good ideas, one thing that could corrupt the memory is a corrupt domain name in the infra cache key; that would calculate the wrong size for it.  There were fixes for domain names passing the validity checks in 1.10.1, it could be interesting to see if those domain name fixes managed to also affect this for you.  But it does not really have anything to do with reloads in that case, maybe just some servers that do it and it creeps up, the infra flush all clears it and forces the counter to a correct value again, perhaps.  Probably not really, it would just store the invalid domain name and not have issues, still it may be good to check.  It would be nice to be able to reproduce, it, perhaps particular queries, but finding them may be hard, like divide a query list in half every time to bisect to them.
Did you also say that this only happens with ECS turned on?

**Comment by leoleovich** [comment]
@wcawijngaards to be honest I am not sure anymore it's ECS related. We were suspecting it as we turned on ECS around the time leak was detected.
At this moment we only sure that flush_infra mitigates the problem.
We will try unbound 1.10.1 soon and come back with the result.

**Comment by ahrar25** [comment]
@leoleovich Did you came up with any results, i've facing the same issue, Below are my configs for cached items

	# edns-buffer-size: 4096
	# msg-buffer-size: 65552
	msg-cache-size: 1G
	msg-cache-slabs: 16 
	# num-queries-per-thread: 1024
	# jostle-timeout: 200
	rrset-cache-size: 1G 
	rrset-cache-slabs: 16 
	 cache-min-ttl: 900
	 cache-max-ttl: 86400
	# infra-host-ttl: 900
	infra-cache-slabs: 4
	# infra-cache-numhosts: 10000

![DNS-1-Memory](https://user-images.githubusercontent.com/58546308/93057611-a657a100-f687-11ea-9337-f7d9fd2ba60e.png)
![system memory](https://user-images.githubusercontent.com/58546308/93057615-a788ce00-f687-11ea-8ddf-799f2168aafd.png)

**Comment by wcawijngaards** [comment]
If you configure both the message-cache and the rrset-cache to use 1G, that is 2G in total, so there is not actually more use than you want?

**Comment by ahrar25** [comment]
@wcawijngaards 
I have reduced the following to 500mb, Memory Utilization is now stable at 60 to 70% from last 6 hours...
rrset-cache-size: 500m
msg-cache-size: 500m

Do i have to keep anything else in mind after i've reduced the the above two to half?

**Comment by wcawijngaards** [comment]
It looks good.  We recommend the rrset cache 2x the size of the msg cache.  Also, some memory allocators grow eventually to about double the size indicated, due to fragmentation and allocation gaps; but your memory allocator may also be different.  We have some advice on https://www.nlnetlabs.nl/documentation/unbound/howto-optimise/

**Comment by pmazzini** [comment]
This is no longer an issue after 1.19.x
