### ISSUE TITLE
Feature request: compiled zones

### ISSUE THREAD

**Issue by edneville** [NLnetLabs/unbound#290]
Hello,

I look after a hideously large zone (eleventy one hundred megabytes). Currently it is handled as a compiled tinydns cdb file and distributed to my cluster of NS servers. I'd very much like to move my operation to unbound and am looking for a method to do this in one place only and distribute a binary lookup file without holding the zone fully in memory. Ideally something like BDB.

Ed

**Comment by wcawijngaards** [comment]
No, we don't do this.  For our authority server (NSD) we used to have precompiled zones, and it still does, but from zonefile contents.  It turned out that the binary format on disk was not actually faster to read from (or faster enough) to keep having it around.  And the plain-text zonefiles are much easier to manage.  Also, for NSD, it serves from memory, not from disk.  Because of reading it in memory, NSD can serve a high query rate.

Unbound also serves from zone files that it reads into memory.  You could distribute the zonefiles to the machines with either Unbound or NSD and then reload them to reread the content when it is updated.

You seem to be asking for an authority server, which is why I mention NSD, which is our authority server software.  https://github.com/NLnetLabs/NSD and https://www.nlnetlabs.nl/projects/nsd/about/ .
But Unbound can also serve authority zone files, with the `auth-zone` config.  Usually for authority servers people want to separate the authority server and the cache, hence separate servers for that.  Unbound's auth-zone feature is used to have a local mirror copy of the root, mostly.

**Comment by edneville** [comment]
Thanks - I'll dig around :-)
