### ISSUE TITLE
[question] reload and keep the cache

### ISSUE THREAD

**Issue by pmazzini** [NLnetLabs/unbound#302]
During config reload the cache is flushed. It makes sense because the cache depends on the config (stub/forward zones, etc).

However, for performance reasons it would be nice to be able to keep it.

I am opening this issue to know your opinion about it and how tricky would it be to do it.

Thanks

**Comment by wcawijngaards** [comment]
It would not be very tricky to do it, but what you say is the problem.  Also trust anchors can change, and that would put items in the cache with the wrong security classification, causing stuff like dnssec-valid when it is not and vice versa flags.  Avoiding the issues caused by changes in config requires a bunch of items to be removed from cache, figuring out exactly which ones is going to be very hard, to get right.  So I would not want to do it.  Keeping the cache around, but perhaps it is garbage, is easy.

**Comment by pmazzini** [comment]
Ok, thanks. I guess that answers my question.
