### ISSUE TITLE
outgoing tcp to unknown ipv6 link-local 

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#315]
unbound 1.11.0

```
module-config: "dns64 respip validator iterator"
dns64-prefix: fd30:d64c:1eed::/96
```

ULA fd30:d64c:1eed::/48
____

unbound log exhibits frequent entries:

> error: outgoing tcp: connect: Invalid argument for fe80::21b:aabb:9765:7231 port 443
> error: outgoing tcp: connect: Invalid argument for fe80::21b:aabb:9765:e31 port 443

Both link-local address are alien to the node and dumping the unbound cache I could not find either, just a bunch of this sort:

```
apple.com.	2523	IN	SOA	nserver.apple.com. hostmaster.apple.com. 2010120084 900 900 2016000 14400
;rrset 616 3 0 5 2
apple.com.	616	IN	AAAA	fe80::21b:aabb:118e:a03b
apple.com.	616	IN	AAAA	fe80::21b:aabb:11ac:e02f
apple.com.	616	IN	AAAA	fe80::21b:aabb:11b2:603b

prod.mozaws.net.	244	IN	SOA	ns-1260.awsdns-29.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
;rrset 4 1 0 5 2
autopush.prod.mozaws.net.	4	IN	AAAA	fe80::21b:aabb:23a5:72be

github.io.	350	IN	SOA	ns-1622.awsdns-10.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
;rrset 350 4 0 5 2
github.github.io.	350	IN	AAAA	fe80::21b:aabb:b9c7:6c99
github.github.io.	350	IN	AAAA	fe80::21b:aabb:b9c7:6d99
github.github.io.	350	IN	AAAA	fe80::21b:aabb:b9c7:6e99
github.github.io.	350	IN	AAAA	fe80::21b:aabb:b9c7:6f99
```
I suppose that all those (alien) fe80::21b entries are unbound synthesised addresses but not matching `dns64-prefix: fd30:d64c:1eed::/96`

As for  `fe80::21b:aabb:9765:7231 port 443` |  `fe80::21b:aabb:9765:e31 port 443` I suspect (due to port 443) those are synthesised from ipv4 of forwarders.

The cache dump shows plenty of records that are compliant with `dns64-prefix: fd30:d64c:1eed::/96`, e.g.

`github.githubassets.com.	3047	IN	AAAA	fd30:d64c:1eed::b9c7:6d9a`

and thus it is not clear why it works as expected for some but generates alien local-link addresses records for others.

**Comment by wcawijngaards** [comment]
The log entries are not because of the dns64 module, they are from the iterator.  It tries to connect to the AAAA, and the kernel does not allow connections to those IPv6 addresses.   So, unbound attempts to call connect() to the fe80 AAAA address to open a TCP channel there, but that fails, the kernel says `Invalid argument', presumably that fe80 address.

fe80 is for neighbors, or local to a link addresses I thought, in IPv6.  I think this is why the kernel rejects it, eg. no link with that address is up.

If I dig over here for those AAAA records, none of them exist, so they look like they have been synthesized for you.  But with the wrong prefix.

**Comment by ghost** [comment]
So it seems that the issue is unrelated to DNS64, also changed unbound's config to `module-config: "respip validator iterator"` and restarted it and the log still prints

```
error: outgoing tcp: connect: Invalid argument for fe80::21b:aabb:9765:7231 port 443
error: outgoing tcp: connect: Invalid argument for fe80::21b:aabb:9765:f631 port 443
```

I do not see why unbound should try to connect to those server addresses in the first place, assuming those connection attempts are to an authoritative NS (port 443) instead of the  upstream resolvers specified within

```
forward-zone:
  name: "."
  forward-addr:
```

Could RR type 65 (Service binding and parameter specification via the DNS) be the cause of this, i.e. the upstream resolver not being able to handle this type, or being misconfigured and providing wrong records, and  and the local unbound instance then trying to iterate with the erroneously stipulated fe80:: prefix.

Else I am having a hard time to understand the source of it, checked RPZ and other transferred zones but none hints remotely at fe80.
____

The curious part is also the common denominator of fe80::21b:aabb as prefix for both, the connection attempts and RR like this one, which suggests that source of providing those erroneous is the same. 
```

githubstatus.com.	562	IN	AAAA	fe80::21b:aabb:b9c7:6c99
githubstatus.com.	562	IN	AAAA	fe80::21b:aabb:b9c7:6d99
githubstatus.com.	562	IN	AAAA	fe80::21b:aabb:b9c7:6e99
githubstatus.com.	562	IN	AAAA	fe80::21b:aabb:b9c7:6f99
;rrset 562 1 0 2 2
githubstatus.com.	562	IN	SOA	ns-1330.awsdns-38.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
;rrset 3262 4 0 5 2
githubstatus.com.	3262	IN	A	185.199.108.153
githubstatus.com.	3262	IN	A	185.199.109.153
githubstatus.com.	3262	IN	A	185.199.110.153
githubstatus.com.	3262	IN	A	185.199.111.153
;rrset 562 1 0 2 2
```

**Comment by wcawijngaards** [comment]
Somehow unbound received those AAAA records from the upstream.  If they are not in your config.  Type65 is not used by Unbound 1.11.0.  Also dns over https is not in 1.11.0, that is 1.12.0.  So, I guess you are using dns over tls?  Otherwise unbound would also not try to open a TCP connection.

Your upstream forwarder must send those AAAA records.  Also there must be some stub-zone configured, otherwise the iterator should not open a AAAA connection there.

Unbound also opens tcp connections to fetch auth zones.  Perhaps you have an auth zone with https urls configured and those get the fe80 addresses from your upstream?

**Comment by ghost** [comment]
> Your upstream forwarder must send those AAAA records

I suspect now as much. With 50+ upstream forwarders specified it will take a little while to figure out the bad apple, unless unbound has a monitoring facility that could show  (filter) the upstream source for those fe80::21b:aabb records - raising the global log level to 3 or 4 it just a bit overwhelming in a production environment.
____
> Also dns over https is not in 1.11.0, that is 1.12.0. So, I guess you are using dns over tls? Otherwise unbound would also not try to open a TCP connection.

Yes, DoT is in play, mostly via port 853 but some of the upstream instances also provision port 443.
_____
> Also there must be some stub-zone configured

on the local unbound instance there is no stub-zone cofigured.
____
> Unbound also opens tcp connections to fetch auth zones. Perhaps you have an auth zone with https urls configured and those get the fe80 addresses from your upstream?

The auth zones are not URL specified but I got a couple of RPZ that are URL HTTPS configured, yet I do not see how those could be the cause since neither provides a RR for their own domain.

**Comment by wcawijngaards** [comment]
Yeah those RPZ zones with HTTPS URL are fetched like an auth zone, so if another forwarder from your long list returns fe80 addresses for that URL then unbound attempts to connect there.

`private-address: fe80::/10` removes all the fe80 stuff.  But does not say which one is doing it.

You could set `do-not-query-address: fe80::/10`, that does not remove the AAAA records, but instructs the iterator.  But since it is a zone download, it would not work and still attempt to download the zone from there.

If you enable logging you should be able to grep for it with `sanitize: removing public name with private address` that `private-address: fe80::/10` makes when those AAAAs are removed.

**Comment by ghost** [comment]
> If you enable logging you should be able to grep for it

which log level should that be, 2 already sufficient or 3 or 4?

**Comment by wcawijngaards** [comment]
At log level 3 and higher, it prints the private address log lines.

**Comment by ghost** [comment]
Thanks, meantime without the log debugging I reckon I figured the bad apple being https://blahdns.com

**Comment by ghost** [comment]
The upstream operator meantime fixed the issue, no more DNS64 records to querying downstream clients.

And thank you for the input to get this sorted. Only wish if like unbound-control could somehow be of assistance to provide some input for such issue, not having to go through raising the log verbosity and grep filtering the log
