### ISSUE TITLE
[feature suggestion] differentiate ipv4/6 traffic up/downstream

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#34]
In the current implementation (1.9.1) ipv4/6 traffic can only be turned on globally but does not provide an option to selectively set ipv4/6 per upstream or downstream.

It would be appreciated if such option could be provided, improving granularity between upstream and downstream.

**Comment by wcawijngaards** [comment]
It is possible to list the IP-addresses to use for upstream and downstream, with outgoing-interface: and interface: statements.  If you only list IPv4 or only IPv6 addresses for them it uses only that protocol to make connections.  Perhaps this can provide a workaround for this feature for you?

**Comment by ghost** [comment]
The suggestion was sparked by https://github.com/NLnetLabs/unbound/issues/35. Once that is sorted it probably does not matter any more.
____
> It is possible to list the IP-addresses to use for upstream and downstream, with outgoing-interface: and interface: statements.

Of course, missed that logic - however, I would prefer to retain randomness  for outgoing queries to counter spoofing.

**Comment by wcawijngaards** [comment]
Okay!  Outgoing queries are still randomized if you do that.  It uses the available addresses and destinations for the randomization.  I mean, it randomizes over the compatible destinations.  And if you give more than one outgoing-interface of that address family (several IPv6 addresses, for example) it'll randomize over the source as well, whilst keeping the IPv4/6 correct.  (Just a note, because you wanted to keep the randomization, this is how you get that) :-)
