### ISSUE TITLE
forward-zone returns REFUSED, unbound returns SERVFAIL

### ISSUE THREAD

**Issue by crolfe** [NLnetLabs/unbound#342]
Hi there,

I have configured Unbound to send all queries to a forward-zone, and there is a particular query that the forward-zone  always returns a REFUSED rcode.  However, it appears that Unbound [will always return a SERVFAIL back](https://github.com/NLnetLabs/unbound/blob/8fd489ea69b7da551ad8f6ba8291d8d8743af016/iterator/iterator.c#L1922).  

I would greatly prefer to be able to return REFUSED, as this makes it clearer to the client that there's a problem with their query, not with the server they are talking to.  Am I missing something?  If not, is it possible to either change this behaviour, or make it a config option to return the original rcode from the forward-zone?

I am happy to provide more details/config etc if that's useful.

**Comment by gthess** [comment]
Hi,
As per DNS, Unbound cannot return REFUSED in this case because Unbound does not refuse to process the query.
The upstream server refuses to process the query and Unbound rightfully returns SERVFAIL because there was an error while resolving the query.

There is current RFC work to extend the error code and [section 4.23](https://datatracker.ietf.org/doc/html/rfc8914#section-4.23) describes the error code in this case.

We haven't implemented the RFC yet in Unbound, but we are planning to do so in the foreseeable future.

**Comment by gthess** [comment]
Linking https://github.com/NLnetLabs/unbound/pull/604 here as it will provide the Extended EDNS Error code for these kinds of answers.

**Comment by gthess** [comment]
Closing this as a non issue.
