### ISSUE TITLE
SAD DNS attack

### ISSUE THREAD

**Issue by dtouzeau** [NLnetLabs/unbound#346]
Hi what is the correct way to protect unbound against the SAD DNS attack ?

[https://thehackernews.com/2020/11/sad-dns-new-flaws-re-enable-dns-cache.html](url)

**Comment by ghost** [comment]
* patch https://github.com/NLnetLabs/unbound/commit/26aa550bd246079b26366627fecbbe7d6e30dabd
* rate limit icmp per IP address via firewall (and block potentially offending nodes)
* if the OS is Linux make sure the kernel is carrying this patch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/patch/?id=b38e7819cae946e2edf869e604af1e65a5d241c5
* leverage TCP connectivity to upstream nodes, e.g. DoT, instead of UDP

Then there are DNS cookies https://kb.isc.org/docs/aa-01387 but such is not widely implemented in the industry and if I am not mistaken not supported by _unbound_ either

**Comment by gthess** [comment]
The patch will not mitigate the attack. It will only make the attack slightly harder.
Ratelimiting on the firewall will also not completely help.
The correct approach is an updated network stack (kernel) that will randomize the ratelimit.
If that is not possible or convenient you can consider blocking outgoing ICMP Port Unreachable messages; that could also prove inconvenient for other reasons (eg. network troubleshooting).
DNNSEC and TCP help but they are not always available.

Just today we released a blog that discusses the attack with regards to unbound: https://blog.nlnetlabs.nl/sad-dns-side-channel-attack-and-unbound/.

**Comment by ghost** [comment]
patch https://github.com/NLnetLabs/unbound/commit/9cc8aa1ddfc42ec9e8dc0607f1f051c89de55c65 seems to add connected UDP sockets, in an effort to harden against the attack vector, something that been mentioned in the research paper

**Comment by marka63** [comment]
Deploying DNS COOKIE with fallback to TCP if valid DNS COOKIE is not present in response will defeat SAD DNS.

Perfect doesn't need to be the enemy better.
