### ISSUE TITLE
How to prevent forwarding query without any dot or domain part?

### ISSUE THREAD

**Issue by laggardkernel** [NLnetLabs/unbound#349]
In `dnsmasq`, settings `domain-needed` and `address=//` could both return `NXDOMAIN` results to prevent forwarding domain without any dot or domain part.

Is there any solution in `unbound`? I tried `local-zone: "." always_nxdomain`, while `"."` seems to match any/all domain.

Those queries without any dot come from Chrome when setting "use a prediction service to help complete searches and URLs typed in the address bar" is checked and no search domains (e.g. `lan`) is assigned on one's computer. And those queries could leak what users search to upstream DNS. Although it could be solved by uncheck the setting in Chrome, I deem preventing forwarding those queries on a local DNS resolver a more universal solution.

FYI, the feature "use a prediction service to help complete searches and URLs typed in the address bar" in Chrome causes huge traffic on root DNSs. [Chromium’s impact on root DNS traffic](https://blog.apnic.net/2020/08/21/chromiums-impact-on-root-dns-traffic/). I personally care more about privacy but not the traffic on root DNSs.

**Comment by gthess** [comment]
Since unbound 1.7 you can use `aggressive-nsec: yes` to use cached covering NSEC answers to generate the NXDOMAIN answers you want for DNNSEC zones (ie. the root). The caveat is that this will work progressively as more and more NSEC records are cached.

SInce unbound 1.8 you can use the `auth-zone` clause to have unbound transfer the root zone locally and reply from that local data without contacting the root. You can find example configurations [here](https://tools.ietf.org/html/rfc8806#appendix-B.2) and [here](https://tools.ietf.org/html/rfc8806#appendix-B.4) and more information about the `auth-zone` options in your local manpage or [online](https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/)(latest version).

For the future, for such support questions I would recommend the [unbound-users mailing list](https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users). Other enthusiastic and experienced  Unbound users are also subscribed to this mailing list and can also provide useful input and answers to your questions.

Hope that helps!

**Comment by gthess** [comment]
Also closing this issue; feel free to reopen if something is not clear.

**Comment by laggardkernel** [comment]
Thanks for you help. I'm not sure this is want I'm looking for. I use unbound as a forwarding DNS server. What I want achieve is to forward all queries to a public DNS server like 8.8.8.8, but prevent forwarding when no `.` is contained in the query in case no search domain is configured on the OS.

**Comment by gthess** [comment]
The `aggressive-nsec` option will _eventually_ do what you want as it can use cached NSEC records to prove that a TLD (Top Level Domain) does not exist. Thus returning NXDOMAIN without the need to contact the root (or the forwarder in your case).

The `auth-zone` will make unbound aware of the contents of the root zone (i.e., all TLDs). All TLD queries (i.e., "when no `.` is contained in the query") will be answered by unbound then without the need to ask the forwarder. The answer will either be delegation information in case the TLD exists, or NXDOMAIN for the rest.

Unless I totally misread your intention, I believe `auth-zone` is exactly what you need.

**Comment by mikahe** [comment]
`auth-zone` does work, but only if you create one for each TLD, so in practice this is infeasible solution, except for such a limited use case.

If you set the `auth-zone` `name` to `.`, nothing resolves.
If you also set `fallback-enabled: yes`, then everything resolves, but also queries getting NXDOMAIN answer are every time going to fallback, i.e. forwarded.
