### ISSUE TITLE
DNSTAP logging in Unbound-1.11.0

### ISSUE THREAD

**Issue by iruzanov** [NLnetLabs/unbound#365]
Hello, Wouter!

As i said earlier i have made patches set for Unbound-1.11.0 to log over DNSTAP both addresses - source (from client) address and destination (local or service) one. My core idea is to introduce NSD-like structure called unbound_socket and use it in comm_points of netevent code. So please look in my patches, i hope they will be reasonable and secure for application.
And only one TODO that i have to do in future - right now i can log only the front side, i.e. client requests and responses. Upstream side is currently logged as 0.0.0.0 local address. Its a question of some rework of outside_network code.

All the patches are in attached tarball.

Thank you in advance!
[patches.tar.gz](https://github.com/NLnetLabs/unbound/files/5659923/patches.tar.gz)

**Comment by wcawijngaards** [comment]
You have to use `freeaddrinfo` for the free of `list->socket->addr` at listen_dnsport.c 1544.
I would prefer a couple of mallocs of the socket struct to be calloc, so that it is zeroed.
The malloc and free in the daemon worker handle routine to make the dst addr is cumbersome and it appear not really needed, it could put a struct sockaddr_storage on the stack there and pass that to the routine that fills the structure (now mk_local_addr that mallocs).  That would be faster and a lot of dnstap users value their speed.

Other than those initial review comments, it looks okay!  I can make those changes, or you can if you feel like it, and then it needs a bit more time from me to get a more detailed review.  Thanks for the re-submit of this with the bugs fixed that you found.

**Comment by iruzanov** [comment]
Ohh, yes! It was my stupid mistake about freeaddrinfo().
And i agree with you about malloc(), - it was my blind paranoia to fetch new memory regions for every step in program :)) So it is a question of good program optimizing. Thank you for the valuable clarifications! Could you please to make the changes that you found by yourself? And then when you are done with detailed research i would like to download the final code to find out all the my mistakes ;) Also it would be great to get binary package with patched code of Unbound-1.11.0

**Comment by wcawijngaards** [comment]
I have created a branch and pull request at #367 .  There I imported the patches you linked in the tar.gz file, and then made the changes and some merge fixes and bug fixes.  You can review the code there.

A tarball with the code repository of today with the state of that code now is here https://nlnetlabs.nl/~wouter/unbound-1.13.1_20201209.tar.gz

The diff for the updated patches can be downloaded in this link https://patch-diff.githubusercontent.com/raw/NLnetLabs/unbound/pull/367.diff

**Comment by iruzanov** [comment]
Great work, Wouter!

And i looked into my patches for your changes and understood that mk_local_addr() was just like a ballast in the code :)) I completely forgot that we can pass repinfo->c->socket->addr directly to dt_msg_send_client_* functions. And also there are more accurate callocs/free in listen_dnsport.c source code. Looks great! Thank you very much!
So now i can download fresh tarball of Unbound!

Also i have made the same patches for NSD-4.2.2. There is more simplier code. And later i will send you the patchset to ask you to review the code for its correctness and optimality.

**Comment by wcawijngaards** [comment]
Applied your contributed code with review from my colleague @gthess from the linked pull request.  Thanks for the contribution!
