### ISSUE TITLE
Failing to resolve aliexpress.com

### ISSUE THREAD

**Issue by polesapart** [NLnetLabs/unbound#419]
[Here is a gist](https://gist.github.com/polesapart/d6f9e1f8fd72611456c2cee89521785d)

**Comment by gthess** [comment]
I am not sure what am I looking at.
aliexpress.com does not appear in the log file.

**Comment by gthess** [comment]
Nevermind, github shows a truncated version by default.

**Comment by gthess** [comment]
I don't see a problem in unbound 1.9.4 or in the latest version (1.13.1) since both work for me.
From the log output I see that unbound does not receive answers from the nameservers for aliexpress.com. These are ns1.alibabadns.com and ns2.alibabadns.com.
I suspect this is a network issue on the machine unbound runs on.
You could try checking the connectivity to those nameservers (`ping`) or even trying contacting them directly
`dig @ns1.alibabadns.com aliexpress.com`
to see if you get different results from unbound. Of course these tests need to run from the same machine unbound runs from.

**Comment by polesapart** [comment]
Oh, I see. Indeed it fails with dig for some reason. Guess I'll have to somehow ask an upstream server as a proxy then. Thanks

EDIT: for anyone else, this did it for me:
`forward-zone:
	name: "aliexpress.com."
	forward-addr: 1.1.1.1
	forward-addr: 8.8.8.8
	forward-first: yes`

**Comment by gthess** [comment]
No problem, closing this then.
