### ISSUE TITLE
local-data for DNSSEC signed zone causes SERVFAIL on Windows Server 2019

### ISSUE THREAD

**Issue by mrimann** [NLnetLabs/unbound#435]
Hi

I think the following issue is not directly related to Unbound in the sense of a bug or missing feature in Unbound. But we ran into the following problem and maybe there's an easy solution to it - be it on the Unbound config side, or on the Windows server. I hope someone had the same issue before and knows a solution.

The setup we're talking about is an office network with an Active Directory setup. The existing DomainController (Windows 2012) is the Nameserver all the clients get assigned via DHCP and is configured to two forwarders, both of those are Unbound resolvers.

The unbound resolvers are configured to just resolve any request from certain subnets - including the network with the AD DC in it. In addition, DNSSEC validation is done by Unbound. DNSSEC validation on the Windows DNS server is disabled. The only "special" config is, that we have some few "local-data" lines in it, to provide network-internal devices with a different answer than on the public internet (via the authoritative nameservers). With this setup, everything worked fine for the last years.

Shortened config (and anonymized):
```
server:
        interface: 0.0.0.0
        interface: ::0
        access-control: 192.168.105.0/24 allow
        verbosity: 1
        local-data: 'app.company.tld. A 192.168.105.63'
```

In this scenario "company.tld" is a publicly resolvable domain that is DNSSEC signed. The entry "app.company.tld" is also in the public zone and resolvable from the authoritative servers, resulting in a public IP - but within the network Unbound is configured to serve an internal IP for this application.

Now we've added a new server to take over the role of the Domain Controller in this Active Directory - and also the role of the DNS server. The config is basically the same: Windows Server 2019 to forward all requests to the two Unbound based Resolvers.

The problem is now, that those hostnames that are configured in Unbound as "local-data" entries, are causing a SERVFAIL as soon as the new Server tries to resolve them for a client.

To narrow it down we performed the following tests:

- On a client: `dig app.company.tld @resolver01.company.tld` = OK (e.g. the end client is able to get the name resolved if asking directly at the resolver)
- On the new Windows Server: `nslookup app.company.tld IP_OF_RESOLVER` = OK (e.g. the Windows server is able to reach the unbound resolver (e.g. no firewall blocking on the way) and is allowed from the unbound config to be served and get's the request resolved when acting as a client)
- On a client: `dig app.company.tld @IP_OF_NEW_WIN_SRV` = SERVFAIL (the client is not able to get an answer, when asking the Windows Server, as the Windows Server in this situation seems to validate DNSSEC for this name which is correctly failing)

As a counter-test, we tried to resolve a random hostname that we know exists in that zone, also via the new Windows Server (that in turn asks Unbound for it), and this strangely works:
- On a client: `dig other-hostname.company.tld @IP_OF_NEW_WIN_SRV` = OK

So far I understand the problem like this: Windows Server 2019 is aware that "company.tld" is in fact DNSSEC signed - but get's unsigned answers he does not trust for those hostnames we override via "data-local" config lines. But Windows Server 2019 seems to be missing the config option to enable/disable the validation of DNSSEC.

Any hint would help :-)

**Comment by wcawijngaards** [comment]
If you are looking for comments from other users, I would think that our users mailing list would be the appropriate place to solicit this kind of feedback.

The issue is that you are inserting a DNSSEC non signed item into the DNSSEC zone.  You are the owner of this zone, so this is fine, and it is possible to set DNSSEC right because you have the keys to sign for that.  There are several changes that would make it work if you use the signing capability to modify things.

You could sign the address in the local data with the correct keys.  Do not forget this has an expiry date and needs to be renewed.  Because I think that unbound will serve the RRSIG with the data item when asked and that should work with DNSSEC validation.  Unbound does not actually do full DNSSEC for local-zones, but can hand over an RRSIG with the data.  If you end up needing more, you then end up signing a (modified) version of the company.tld zone and serving it on an authority server.  This is a second solution, and then those keys either need to be the same as the publicly available ones from the public chain of trust, or would need to be loaded into every dnssec validator as a trust anchor.

You could also create a new set of keys for this zone and sign it, and then dnssec is okay, but you need to load these keys into unbound as a trust anchor so that unbound can validate it.  Also for the downstream dnssec validating server you have to add a trust anchor for this zone then.

You could also have the data be under an unsigned delegation, eg. have an unsigned zone, and this means there is a signed zone as a parent zone that is signed to create an insecure delegation.  Then there is no need to have DNSSEC signatures over your local-data item.

**Comment by mrimann** [comment]
Thanks for your feedback. You're right, the mailinglist would have been a good place to ask :-)

We've decided to get rid of those unsigned items in the signed zone (which was a hacky work-round anyway) and thus there's no need to change or fix something in Unbound itself, that's why I'll close this issue.
