### ISSUE TITLE
Feature Request: include: compressed.conf files?

### ISSUE THREAD

**Issue by vollkommenheit** [NLnetLabs/unbound#436]
I have compiled two separate block-list files from various sources, one 20MB (~400,000 lines), and the other 5MB (~200,000 lines). Trouble is, my openwrt router with 128MB RAM would run out of memory if either of one those lists is included via the "include: " directive. OTOH, my desktop host with 32GB of RAM runs unbound with both of those fine (although it takes 30+ seconds for unbound to finish initializing). 

I realize the simpliest solution is to move unbound/DNS-based blocking to a mini-PC with more RAM. However, since modern web browsers could accept HTTP compression such as gzip, I'm wondering if it'd be possible to similarly have unbound's "include: " optionally handle compressed .conf files at runtime on the fly, in order to avoid out of memory issues such as the above (if only loading compressed conf file into the memory and processing it without expanding is possible), or out of flash storage issues on even older routers which I've run into as well.

**Comment by gthess** [comment]
I am guessing that those block-list files are a stream of local data directives.
In that case the problem is not the size of the files but the resulting size of all those zones that unbound needs to store in memory to be able to block these zones. Only more memory could help you there.
Unless I misread something.

**Comment by vollkommenheit** [comment]
@gthess that makes sense. Thanks. Closing now.
