### ISSUE TITLE
Doubt regarding unbound with redis

### ISSUE THREAD

**Issue by cardosocristian** [NLnetLabs/unbound#452]
What is the correct way to clear a DNS note from the unbound / redis cache?
Just executing the unbound cache management commands on my server had no effect on the redis cache.
Is there any good recommended practice?

**Comment by gthess** [comment]
The unbound cache management commands are for a specific unbound instance.

The redis cache is supposed to be used by different unbound instances.
There is no correct way on doing this as it relies heavily on timing and what is cached where at a given time, since all the unbound instances can update each other's cache through redis given the correct input queries.

If you have that right then for deleting something from redis you would need the relevant redis-cli commands.
I can point you to the redis key generation that happens at
https://github.com/NLnetLabs/unbound/blob/13e445d50b6e2a9441d9364d4213a57781d9e6f1/cachedb/cachedb.c#L331
which is essentially a sha256 hash of (the query name, type, class and the configured secret-seed) encoded in hex.

**Comment by gthess** [comment]
Closing this. Feel free to ping me here if something was not clear.
