### ISSUE TITLE
Unbound Edgeos

### ISSUE THREAD

**Issue by HellsAngel79** [NLnetLabs/unbound#456]
Hi,
Im kinda new to linux but managed to install dnscrypt on an edgerouter 12 their github provides the binaries for this router think its
a mips cpu, i wanted to install unbound and the one on the repo by edgeos is like 6 years old is there anyway this github can provide the binaries aswell? or is there anyway to install a recent version of this on edgeos? any help is much appreciated.

**Comment by gthess** [comment]
Hello,
We do not provide binaries; only source code. Binaries are managed by the package maintainers for the different distributions.

The only exception for that are windows binaries which we offer as a low-maintenance community service because compiling on these systems is not the easiest thing to do.

I am not accustomed with EdgeOS but it seems to be a linux variation. Compiling the source code on the system should be possible. Cross-compiling for that system should also be possible.

You can also ping the EdgeOS package maintainers to see if they are willing to provide newer packages.

You can also try to reach other unbound users, that may have similar experience, on the official mailing list at https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users.

I hope that this was useful somehow but unfortunately I cannot help you further; closing this issue.
