### ISSUE TITLE
unbound-control error if unbound is started with custom config filename

### ISSUE THREAD

**Issue by SasanKSMC** [NLnetLabs/unbound#46]
When the unbound is started with the custom config file name:
`./unbound -c custom.conf`

custom.cof:

remote-control:

      

control-enable: yes
      control-interface: 127.0.0.1
      control-port: 8953

Running the following unbound-control command will result in the error:

linux:/usr/local/etc/unbound# unbound-control dump_cache -s 127.0.0.1
[1561341472] unbound-control[19082:0] error: Could not open /usr/local/etc/unbound/unbound.conf: No such file or directory
[1561341472] unbound-control[19082:0] fatal error: could not read config file

I don't know whether it is a bug or my misunderstanding of the documentation.

**Comment by wcawijngaards** [comment]
I think the solution is
`unbound-control -c custom.conf status`
But you also give a -s 127.0.0.1 option.  This wants to read the /usr/local/etc config file and then override the IP address to 127.0.0.1 (that was already 127.0.0.1).
What documentation or option could be improved to make it easier to find out (or add an option to make it easier to use somehow?).

**Comment by SasanKSMC** [comment]
I think `-s` option becomes obsolete when the config file name is not the default. Or if the `control-interface` in the config file is different from IP address given in `-s` (Obviously!). Probably `-s` should be removed after all since I cannot find any unique advantages of using it independently?

**Comment by wcawijngaards** [comment]
Yes the `-s` looks not useful for you, here.  It is useful in (test) cases elsewhere.  The config file is needed to also signal the names of the files with the TLS keys for the connection.
The `-s` option can be useful if you copy the files and config (snippet with remote-control) to another host, then you can contact the server with the -c and -s options both to specify the files with TLS keys and the -s with the IP-address that is different.  Althought in the file on the other host, you could of course also adjust the ip-address to work.
In newer unbound versions, you can use a local-socket, by specifying a filename for the socket (/tmp/unbound-control.sock or somesuch), and then it uses a local pipe.  The socket in its own directory is good, /run/unbound/unbound-control.sock for example, because then the permissions on that directory and on the file can be used to control access to the service.

**Comment by SasanKSMC** [comment]
Thank you very much. This was very useful.

**Comment by JasonGantner** [comment]
I have a similar issue on 1.9.2:
```shell-session
/ # unbound-control -c /etc/unbound/unbound.conf reload
ok
/ # unbound-control -c /etc/unbound/unbound.conf reload
[1562830044] unbound-control[33:0] error: connect: Connection refused for /run/unbound/control.socket
```
While this can be found in the unbound logs :
```
11/07/2019 09:14:24[1562829264] unbound[15:0] notice: Restart of unbound 1.9.2.
11/07/2019 09:14:24[1562829264] unbound[15:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
11/07/2019 09:14:24[1562829264] unbound[15:0] warning: Continuing with default config settings
```
The behaviour on 1.8.3 is normal

**Comment by gthess** [comment]
So, the first reload command reloads unbound but because the configuration file could not be read unbound starts with the default options. By default the remote control is turned off that's why you can't connect anymore.

This seems like a chroot issue. When unbound initially starts it reads the configuration file and then sets up the chroot environment. When the reload command is issued unbound can't find the configuration file in the chroot environment.

If after checking your configuration you still have issues you can share the following output:
`unbound-control -c /etc/unbound/unbound.conf get_option directory`
and
`unbound-control -c /etc/unbound/unbound.conf get_option chroot`

**Comment by gthess** [comment]
@JasonGantner Where you able to figure out your issue?

**Comment by gthess** [comment]
Closing this one.

**Comment by JasonGantner** [comment]
@gthess Sorry for the delay, I've unfortunately been away for a few month :/

Here's the output :
```shell-session
/ # unbound-control -c /etc/unbound/unbound.conf get_option directory
/usr/local/etc/unbound
/ # unbound-control -c /etc/unbound/unbound.conf get_option chroot
/usr/local/etc/unbound
```

Following your suggestions, I added `chroot: ""` to the config file and this fixed the issue.
(The Unbound server is dockerized so chrooting isn't needed)

Out of curiosity, is this a change of default behavior between 1.8.x and 1.9.x ?
(The issue did not occur with 1.8.x)

Thanks a lot for your help and sorry again for the delay

**Comment by gthess** [comment]
No problem.
There was no change in `chroots`'s default value (default on). Is this a packaged unbound? I suspect that the maintainers may have forgotten to turn off the chroot for the new version.

**Comment by JasonGantner** [comment]
I switched from packaged to self-built to enable GOST support and update to latest stable as soon as available instead of waiting for weeks or more to update. That explains the change in default value. 
My bad.
