### ISSUE TITLE
SPEC file in version 1.13.1 references version 1.4; unable to build RPM from source

### ISSUE THREAD

**Issue by commandline-johnny** [NLnetLabs/unbound#500]
**Describe the bug**
rpmbuild -ta ./unbound-1.13.1.tar.gz fails because SPEC file references version 1.4 instead of 1.13.1. Updating SPEC file with version results in further errors.

**To reproduce**
1. Download unbound-1.13.1.tar.gz from nlnetlabs website
2. Run `rpmbuild -ta unbound-1.13.1.tar.gz

**Expected behavior**
rpmbuild should build binary RPM from source

**System:**
 - Unbound version: 1.13.1
 - OS: CentOS 7

**Comment by wcawijngaards** [comment]
The spec files that are actually used by distros are maintained by themselves, these files are examples that have been contributed. There is contrib/unbound.spec and contrib/unbound.spec_fedora.

These are the fixes to the unbound.spec file so that it works with 1.13.1. It fixes the errors that rpmbuild reports.
```.spec
- ldns and ldns-devel no longer required. Fixed date. Version to 1.13.1.
- Removed symlink %attr mode, made unbound.conf symlink relative.
- Added pkgconfig/libunbound.pc to the packaged files.
```
