### ISSUE TITLE
On Linux Mint I followed an official tutorial for ubuntu, to install it, and this broke my internet  

### ISSUE THREAD

**Issue by Menard01** [NLnetLabs/unbound#590]
Here https://unbound.docs.nlnetlabs.nl/en/latest/use-cases/local-stub.html
It is with the default version of Mint repositories , so it is version 1.9.4

And the default installation doesn't work neither, because there is allready a hidden DNS resolver : systemd-resolved 
 Because of this I stayed 2 years with unbound and believing I was my DNS resolver 
A fix provided by Mint users, works

**Comment by TCY16** [comment]
Hi @Menard01,

Could you point me to the fix you mentioned, because we can maybe use this to improve the docs?

**Comment by Menard01** [comment]
https://forums.linuxmint.com/viewtopic.php?p=2109852#p2109852
Works on Mint 20.1 64bits cinnamon

**Comment by TCY16** [comment]
Thanks for getting back to me!

I see that on the link you posted the solution is to disable systemd-resolved. While this is a perfectly valid solution, in the docs you mentioned we chose to keep the solution as easy as possible for newer users by pointing systemd-resolved to Unbound instead of disabling it. We'll discuss if we feel this solution is easier and adjust accordingly.

Although we are in contact with the package managers, we, the maintainers of Unbound, are not the package maintainers for the different OS distributions, and therefore have no control if the distributions install an older version.

I'm closing the issue for now, as your problem seems solved :)
