### ISSUE TITLE
Undefine-shift in sldns_str2wire_hip_buf 

### ISSUE THREAD

**Issue by JiangHeng12138** [NLnetLabs/unbound#610]
version:  unbound-1.11.0

```
sldns/str2wire.c:2080:10: runtime error: left shift of negative value -524206
    #0 0x5d039c in sldns_str2wire_hip_buf /src/unbound/sldns/str2wire.c
    #1 0x4b2400 in LLVMFuzzerTestOneInput /src/unbound/fuzz_3.c:58:17
    #2 0x443833 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #3 0x42efa2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
    #4 0x434c46 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
    #5 0x45e152 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #6 0x7f4a60869b26 in __libc_start_main (/lib64/libc.so.6+0x25b26)
    #7 0x40ae59 in _start (/root/oss-fuzz/build/out/unbound/fuzz_3_fuzzer+0x40ae59)
```

**Comment by wcawijngaards** [comment]
Took some effort to figure this out, but it seems that a right shift is not using unsigned, but a signed type. By casting to unsigned before that shift, the negative value should go away. The fix has that. It also masks the added value, which is similar to issue #611, so that it cannot integer overflow during the addition of the calculation.

This error could possibly have resulted in a wrong error code or wrong position of the error. The fix should fix it, but I have no reproducer case, the commit applies to the 1.11.0 codebase, or you could use the current repo, if you want to try that.
