### ISSUE TITLE
unbound dropped Windows XP with SP3 since v1.14.0?

### ISSUE THREAD

**Issue by CNMan** [NLnetLabs/unbound#659]
v1.13.2 works fine.but 1.14.0 or 1.15.0 show the error

```
The NtCreateFile API failed. This error should never be returned to an application, it is a place holder for the Windows Lan Manager Redirector to use in its internal error mapping routines.
```
![2022-04-06_000419](https://user-images.githubusercontent.com/8692234/161799359-e31f3b7d-459e-4f41-a730-153c3822a289.png)

**Comment by wcawijngaards** [comment]
It seems we upgraded the mingw toolkit to a point where it stops supporting windows XP. But I am not sure what part of it is causing the issue. In this reference, the discussion says support for XP is getting dropped off, https://github.com/msys2/MINGW-packages/issues/5139 .

But it could also be the fix that adds libssp to be linked with for openssl 3.0.0 compilation. That could be the change.

Or it could be the change that introduced the if_nametoindex function to be called. But if you do not use the feature it should not call the function so that should not fail then.

The unbound.exe does not contain a reference to the string NtCreateFile though. Perhaps it is another function call that causes the problem.

**Comment by CNMan** [comment]
https://github.com/NLnetLabs/unbound/issues/689
