### ISSUE TITLE
I have domain in cloudflare "example.com" , how configure my unbound dns server for subdomain"sub.example.com  -192168.0.1" in local network, for my local users

### ISSUE THREAD

**Issue by vanabazyan** [NLnetLabs/unbound#685]
**Current behavior**
Is there a current behavior that the feature relates to?
If yes, would you wish the current behavior to change?

**Describe the desired feature**
A clear and concise description of what the feature should be.

**Potential use-case**
Describe how you see this feature being useful to other Unbound users.

**Comment by vanabazyan** [comment]
tank you

**Comment by gthess** [comment]
Hi,
If I understand correctly that your local users that are using your local Unbound need to get `192.168.0.1` for `example.com. A` or subdomains of that like `sub.example.com. A` then the following configuration will work:
```
server:
    ...
    local-zone: example.com. redirect
    local-data: "example.com. A 192.168.0.1"
    ...
```
For more information on local-zone options: https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#term-local-zone-zone-type.

Also since this is not an actual issue/bug/feature request we prefer to get this kind of support questions on the mailing list: https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users

**Comment by gthess** [comment]
Closing as inactive and a non issue. Feel free to reopen/tag.
