### ISSUE TITLE
Unittest breaking with error for Centos Stream 9/EPEL 9

### ISSUE THREAD

**Issue by oukb** [NLnetLabs/unbound#691]
**Describe the bug**
Unittest breaking with error with 1.16 and Centos Stream 9/EPEL 9
And worked with 1.15

```
./unittest
assertion failure testcode/unitverify.c:199
Start of unbound 1.16.0+libevent unit test.
test authzone functions
test negative cache functions
test ub_random functions
test per-view respip config data apply functions
test global respip config data apply functions
test per-view respip config actions apply functions
test global respip config actions apply functions
test signature verify functions
test signature verify:./testdata/test_signatures.1
make: *** [Makefile:345: test] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.ZKuflj (%check)
```

**To reproduce**

1. build Unbound 1.16 for any architectures Centos Stream 9/EPEL 9

**Expected behavior**
Successful finishing of all tests

**System:**
 - Unbound version: 1.16
 - OS: CentOS Stream 9

**Additional information**

Log with error
https://download.copr.fedorainfracloud.org/results/fcsm/unbound/epel-9-x86_64/04500704-unbound/builder-live.log.gz

Log without error
https://download.copr.fedorainfracloud.org/results/fcsm/unbound/fedora-36-x86_64/04500704-unbound/builder-live.log.gz

**Comment by wcawijngaards** [comment]
This issue seems likely to be caused by the algorithm disable features in those recent distros. The test comes up to test sha1 and this could be disabled. Also other algorithms could be disabled.

You could compile with the feature switches at compile time to turn off those algorithms, and then the test should succeed. It checks if the algorithms are included before testing them.

But for a more automated test, the same type of runtime checks that are performed for fixing the algorithm usage on this type of deployment could also be used to make the test set perform checks on the algorithms.

**Comment by oukb** [comment]
Thanks
