### ISSUE TITLE
Unbound answer from the wrong IPv6

### ISSUE THREAD

**Issue by kiwixz** [NLnetLabs/unbound#698]
**Describe the bug**
Unbound answers with a different IP than the query was sent to.  Client never gets the answer because it's blocked by the firewalls not recognizing the source IP.
Note: I only tested with IPv6.

**To reproduce**
1. Have an interface with two IPs
2. Send a query to the secondary IP
3. Unbound will answer from the primary IP

**Expected behavior**
Unbound should answer queries from the destination IP of the initial query.

**System:**
 - Unbound version: 1.13.1
 - OS: Ubuntu 22.04
 - `unbound -V` output:
 ```
Version 1.13.1

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-libnghttp2 --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.0.2 15 Mar 2022
Linked modules: dns64 python subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Comment by wcawijngaards** [comment]
Unbound leaves interface selection for the outgoing message to the kernel, and this uses the route table, and this is set to the other address than the one it came in on. Two ways to fix this. Instead of having unbound listen on the generic, default, 0.0.0.0 and ::0 interfaces, bind the two IPv6 addresses specifically by having an interface: line for both of the IPv6 interfaces. This means that the incoming packet comes in on a socket file descriptor that is specific for the IPv6 address, and the reply that gets sent on the socket then gets the correct IPv6 address.

Another way is to bind to the interface name, instead of two entries for the addresses. Unbound then enumerates the interface addresses at start up and uses those.

You can also enable `interface-automatic: yes` in unbound.conf, that makes unbound fetch the source IP of the incoming datagrams with ancillary data, and uses that also for the replies, making sure that the reply comes from the correct IPv6. This works for you as well. It also works in cases where the addresses are not fully known in advance, like in cases where the interface is changed at run time.

**Comment by kiwixz** [comment]
Works like a charm, thanks !
