### ISSUE TITLE
[Q] Persisting custom data between plugin runs

### ISSUE THREAD

**Issue by ngortheone** [NLnetLabs/unbound#745]
I am using pythonmod to write module. A module needs to persist custom data between executions. The data doesn't have to survive unbound restart. An ideal data location is memory, as it needs to be read and modified often. An external process needs to configure the plugin at runtime. Unfortunately stack allocated data vanishes, so I need a proper way to store in on the heap. 

Questions:

- What is the best way to do this with unbound? 
- Are there functions available to append data to the config at runtime and look it up later? 
- Is there a way to set arbitrary key/value pair in configuration via unbound-control or some other mechanism?

EDIT: More questions

**Comment by gthess** [comment]
Hi,

>Unfortunately stack allocated data vanishes, so I need a proper way to store in on the heap.

Using a global variable in your python script should work.

>Are there functions available to append data to the config at runtime and look it up later?

No.

>Is there a way to set arbitrary key/value pair in configuration via unbound-control or some other mechanism?

No.

If you don't need to update these key/value pairs (I assume these are the configuration you are referring to) during runtime then putting them in your script before starting Unbound (or your script reads them upon initialization) would work.

BTW, since this is a support question and not an issue, we prefer the mailing list (community support; https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users) to be used instead of the issues here :)

**Comment by ngortheone** [comment]
What would be the best approach to change plugin configuration at runtime, if I can't append data to the runtime config and use unbound-control?

**Comment by gthess** [comment]
I don't know about best but two things come to mind.

You could either do something with shared memory in python (e.g., multiprocessing.shared_memory) but you would have to write your own "control" script that would write to the shared memory.

Or you could pass the configuration value through a normal "control" query to Unbound (with dig for example).
The value could be part of a special query name and when your module sees that query it reads the value and updates it's configuration. You would need to make sure that the OK answer you would generate back to the client will have 0 TTL so that it is not cached.
For inspiration you can have a look at the python examples (https://github.com/NLnetLabs/unbound/tree/master/pythonmod/examples) especially the calc.py, dict.py and resip.py.

Hope this is helpful; closing the issue by the way since it is not an issue :)
