### ISSUE TITLE
[FR] fallback resolve when not in cache yet

### ISSUE THREAD

**Issue by markg85** [NLnetLabs/unbound#763]
Hi,

Unbound works great! No doubt there!
But the reverse DNS nature also makes it sluggish for initial DNS lookups that aren't cached yet.
While this certainly isn't an issue, having it even better can't be bad. Right? :)

My suggestion is as follows:
When unbound handles a DNS request it should do a couple of things:
1. When it's cashed return it to the user (fast)
2. When it's not cached:
2.1 (in the background) build your cache for that request
2.2 immediately return from a fallback dns (1.1.1.1, 8.8.8.8, .. you get the idea)

My thinking here is that knowing if an entry is cached or not is probably known in microseconds. From that point on you - from the users point of view - either return the cached result or return what public DNS providers have. Giving a net result of always being fast.

And for the next lookup, when unbound has resolved it with reverse dns heuristics, you get the cache back.

There is a little bit of a tradeoff here with privacy and speed. Some people will always opt for the privacy side, some for the speed. And others flip between them. Suffice to say, this probably has to be optional and potentially even disabled by default.

Or is all of this already possible??

Best regards,
Mark

**Comment by saint-lascivious** [comment]
This only really seems to be an issue if the caches are being taken down for any reason with any regularity. Machine or service restarts being the most obvious candidates I suppose.

What I ended up doing in my own resolver stack is providing a persistent cache backend with Redis. Very few distribution binaries ever seem to come with the `cachedb` module available, so if you're not already you'll have to compile your own Unbound binaries and enable/configure `cachedb` but this is trivial.

You can have each Unbound instance have its own Redis database, or have all instances reference a single database, said database may/may not be clustered, etc.

cachedb is checked after initial cache, and if a record exists it's served with a 0 ttl. The upshot of this all being that a service that's been restarted can immediately send an optimistically cached result from the cache backend.

You can also couple this with (after consideration and trial in your network) with `serve-expired` to limit having to check the cachedb backend or having to recurse if you might otherwise have a perfectly good (albeit stale) record in cache already.

**Comment by markg85** [comment]
Hi @saint-lascivious,

I've read your message half a dozen times and still don't understand it fully.

Are you telling me that the unbound cache is, by default, in-memory only? So a restart of the service (or pc it's running on) means the caches start from scratch?

Also, my intention might not have been clear enough.
When you do a DNS request which isn't cached yet, that request can easily take up to even a second.
I'm asking for a way to, when you don't have the DNS in cache at all yet, to basically follow 2 paths.
1. Internally unbound should do it's thing and resolve it.
2. While it's doing that, don't wait but just immediate return whatever a DNS service like 1.1.1.1 returns.

**Comment by saint-lascivious** [comment]
> Hi @saint-lascivious,
> 
> I've read your message half a dozen times and still don't understand it fully.
> 
> Are you telling me that the unbound cache is, by default, in-memory only?

Yes.

>So a restart of the service (or pc it's running on) means the caches start from scratch?

Also yes.

> Also, my intention might not have been clear enough.

You were clear. I'm aware of what you want to achieve, I was trying to point out that, in this author's opinion, it's not really needed at all. Those gruelling long slogs to resolve obscure novel domains should ideally only be happening once, and then the cachedb backend will have the recursed path in long term cache.

If it's a domain you access with any regularity, cache `prefetch` will grab it and keep the cached record fresh in both cache and cachedb.

You could also look into tuning your `fetch-policy` values. By default Unbound will attempt to grab more of the path than it needs to recurse a given result, to assist with future results. This can be somewhat of a double edged sword, or robbing Peter to pay Paul, or whichever idiom you'd prefer. I have my fetch policy set up so that it's grabbing only what's required to satisfy the given query and no more. Somewhat Bind-like.

Another thing you could look into is triggering a cache warmup script on service restart or whenever is convenient to you (small AM hours, etc.). There's a simple yet suitable example of this in the `contrib` folder in Unbound's source.

**Comment by markg85** [comment]
That's very interesting!
Sounds like the default unbound setup, while great already, isn't that well tuned for the local home case where you just "might" have a restart every once in a while.

I'm using pi-hole which uses this unbound dockerfile: https://github.com/MatthewVance/unbound-docker/blob/master/1.12.0/Dockerfile

Now i'm sure i can figure out the redis part, create a new dockerfile, update pi-hole to use that instead and finally have it working... Not really looking forward to that to be honest. Are you aware of a dockerfile + redis configuration? That would be a much easier starting point for me!

**Comment by saint-lascivious** [comment]
No, I'm not aware of such a thing I'm afraid.

To be perfectly honest I don't much understand the use case for Docker outside of circumstances where the host is necessitated to provide 1+N versions of $RANDOM_BINARY dependency.

For example:
 - Service A requires Binary version X
 - Service B requires Binary version Y

Outside of that circumstance, it feels a lot like additional overhead for no reason to me. Though I'm not exactly a hip young whippersnapper anymore.

Ideally, my opinion, your resolution stack should reside on dedicated hardware and perform that function singularly.

**Comment by markg85** [comment]
Hi @saint-lascivious 

Using docker is still dedicated hardware! The beauty, at least the value i have in docker, is that it's easy to migrate from server X to Y when that need arises. A task that's much more involved if it are services running directly on the host machine.

A docker container has barely any overhead - if any. A virtual machine setup however, you might be confusion it with that, has a ton of overhead. I'm not opting to go the virtual machine route.

Anyhow, closing this. Even though your solution isn't what i was looking for initially ;)
