### ISSUE TITLE
SERVFAIL's to www.mass.gov

### ISSUE THREAD

**Issue by dsm1212** [NLnetLabs/unbound#791]
**Describe the bug**
For some reason, I can no longer resolve www.mass.gov. Its a site I use frequently so I know it was working last week. If I go off the network and bypass unbound the site is reachable. 

**To reproduce**
Browse to www.mass.gov or just "dig www.mass.gov" and wait.

**Expected behavior**
The browser should go to the site or dig should resolve the IP.

**System:**
 - Unbound version: 1.17.0
 - OS: I'm using the mvance/unbound docker container on debug bullseye
 - `unbound -V` output:
# unbound -V
Version 1.17.0

Configure line: --disable-dependency-tracking --prefix=/opt/unbound --with-pthreads --with-username=_unbound --with-ssl=/opt/openssl --with-libevent --with-libnghttp2 --enable-dnstap --enable-tfo-server --enable-tfo-client --enable-event-api --enable-subnet
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.0.7 1 Nov 2022
Linked modules: dns64 subnetcache respip validator iterator
TCP Fastopen feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Additional information**
[sample.log](https://github.com/NLnetLabs/unbound/files/10069076/sample.log)

**Comment by gthess** [comment]
It seems this is a problem with the zone rather than Unbound.
https://dnsviz.net/d/www.mass.gov/Y3z7YQ/servers/ indicates that the nameservers of mass.gov are not reachable (at the time of investigation).
A resolver trying to build its cache (like Unbound here) cannot resolve the domain. I guess by "If I go off the network and bypass unbound" you are contacting resolvers which have cached records of the zone.

Btw, the issue seems resolved at this moment.

**Comment by dsm1212** [comment]
I probably lost my own cache when I restarted over the weekend. Yes it cleared up. I'm going to have to stash that dnsviz.net link so I can remember it. Thanks for taking a look!

**Comment by edmonds** [comment]
> It seems this is a problem with the zone rather than Unbound. https://dnsviz.net/d/www.mass.gov/Y3z7YQ/servers/ indicates that the nameservers of mass.gov are not reachable (at the time of investigation). A resolver trying to build its cache (like Unbound here) cannot resolve the domain. I guess by "If I go off the network and bypass unbound" you are contacting resolvers which have cached records of the zone.
> 
> Btw, the issue seems resolved at this moment.

It seems a little bit more complicated to me.

`www.mass.gov` is in the `mass.gov` zone which has these nameservers:

```zone
;; ANSWER SECTION:
mass.gov.		10800	IN	NS	internet-dns1.state.ma.us.
mass.gov.		10800	IN	NS	internet-dns2.state.ma.us.
mass.gov.		10800	IN	NS	internet-dns3.state.ma.us.

;; ADDITIONAL SECTION:
internet-dns3.state.ma.us. 900	IN	A	146.243.122.17
internet-dns2.state.ma.us. 900	IN	A	146.243.165.212
internet-dns1.state.ma.us. 900	IN	A	170.63.70.36
```

These servers will respond with the CNAME for `www.mass.gov`. They'll also send back the DNSKEY for `mass.gov` since the zone is signed. That all looks fine.

Where it gets problematic is if Unbound wants to find the authoritative addresses for those nameserver names (`internet-dns[123].state.ma.us`). They are in the `state.ma.us` zone, which has the same nameservers as the `mass.gov` zone:

```zone
;; ANSWER SECTION:
internet-dns1.state.ma.us. 900	IN	A	170.63.70.36

;; AUTHORITY SECTION:
state.ma.us.		900	IN	NS	internet-dns2.state.ma.us.
state.ma.us.		900	IN	NS	internet-dns1.state.ma.us.
state.ma.us.		900	IN	NS	internet-dns3.state.ma.us.

;; ADDITIONAL SECTION:
internet-dns3.state.ma.us. 900	IN	A	146.243.122.17
internet-dns2.state.ma.us. 900	IN	A	146.243.165.212
```

`state.ma.us` is also signed, but unlike the `mass.gov` zone, these servers **won't** return the DNSKEY for `state.ma.us` over UDP. I'm getting a 0% success rate for UDP, and DNSViz is showing the same.

Compare:

```zone
; <<>> DiG 9.18.8-1-Debian <<>> +norec +dnssec +nocrypto @internet-dns1.state.ma.us -t DNSKEY mass.gov
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29350
;; flags: qr aa; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1220
;; QUESTION SECTION:
;mass.gov.			IN	DNSKEY

;; ANSWER SECTION:
mass.gov.		1296000	IN	DNSKEY	256 3 7 [key id = 50498]
mass.gov.		1296000	IN	DNSKEY	257 3 7 [key id = 21033]
mass.gov.		1296000	IN	RRSIG	DNSKEY 7 2 1296000 20230104154845 20221120151941 21033 mass.gov. [omitted]
mass.gov.		1296000	IN	RRSIG	DNSKEY 7 2 1296000 20230104154845 20221120151941 50498 mass.gov. [omitted]

;; Query time: 40 msec
;; SERVER: 170.63.70.36#53(internet-dns1.state.ma.us) (UDP)
;; WHEN: Tue Nov 22 16:20:48 EST 2022
;; MSG SIZE  rcvd: 925
```

With:

```zone
$ dig +norec +dnssec +nocrypto @internet-dns1.state.ma.us -t DNSKEY state.ma.us                    
;; communications error to 170.63.70.36#53: timed out
;; communications error to 170.63.70.36#53: timed out
;; communications error to 170.63.70.36#53: timed out

; <<>> DiG 9.18.8-1-Debian <<>> +norec +dnssec +nocrypto @internet-dns1.state.ma.us -t DNSKEY state.ma.us
; (1 server found)
;; global options: +cmd
;; no servers could be reached
```

```zone
$ dig +norec +dnssec +nocrypto @internet-dns1.state.ma.us -t DNSKEY state.ma.us +tcp               

; <<>> DiG 9.18.8-1-Debian <<>> +norec +dnssec +nocrypto @internet-dns1.state.ma.us -t DNSKEY state.ma.us +tcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18304
;; flags: qr aa; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1220
;; QUESTION SECTION:
;state.ma.us.			IN	DNSKEY

;; ANSWER SECTION:
state.ma.us.		1296000	IN	DNSKEY	256 3 7 [key id = 48569]
state.ma.us.		1296000	IN	DNSKEY	257 3 7 [key id = 18273]
state.ma.us.		1296000	IN	DNSKEY	256 3 7 [key id = 17873]
state.ma.us.		1296000	IN	RRSIG	DNSKEY 7 3 1296000 20230103102418 20221119092418 17873 state.ma.us. [omitted]
state.ma.us.		1296000	IN	RRSIG	DNSKEY 7 3 1296000 20230103102418 20221119092418 18273 state.ma.us. [omitted]
state.ma.us.		1296000	IN	RRSIG	DNSKEY 7 3 1296000 20230103102418 20221119092418 48569 state.ma.us. [omitted]

;; Query time: 28 msec
;; SERVER: 170.63.70.36#53(internet-dns1.state.ma.us) (TCP)
;; WHEN: Tue Nov 22 16:21:15 EST 2022
;; MSG SIZE  rcvd: 1253
```

All three nameservers seem to be behaving the same way. 0% success rate for `state.ma.us./IN/DNSKEY` via UDP, 100% success rate for `state.ma.us./IN/DNSKEY` via TCP, vs. 100% success rate for `mass.gov./IN/DNSKEY` via UDP or TCP.
