### ISSUE TITLE
Windows version can't verify Let's Encrypt certificates

### ISSUE THREAD

**Issue by Tabiskabis** [NLnetLabs/unbound#849]
**Describe the bug**
`crypto error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`
When trying to forward queries to any DoT server with a Let's Encrypt certificate.

**Steps to reproduce the behavior:**
1. Use as example forwarder: 5.9.164.112@853#dns3.digitalcourage.de
2. Use tls-win-cert, or tls-cert-bundle with a complete letsencrypt certs bundle. Does not matter.
3. Google the issue, find you did what they suggest doing to no avail.

**System:**
 - Unbound version: 1.17.1
 - OS: Windows 10 22H2
<details>
<summary>`unbound -V` output:</summary>
Version 1.17.1  
Configure line: --host=x86_64-w64-mingw32 --build=x86_64-redhat-linux-gnu --target=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --exec-prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --bindir=/usr/x86_64-w64-mingw32/sys-root/mingw/bin --sbindir=/usr/x86_64-w64-mingw32/sys-root/mingw/sbin --sysconfdir=/usr/x86_64-w64-mingw32/sys-root/mingw/etc --datadir=/usr/x86_64-w64-mingw32/sys-root/mingw/share --includedir=/usr/x86_64-w64-mingw32/sys-root/mingw/include --libdir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib --libexecdir=/usr/x86_64-w64-mingw32/sys-root/mingw/libexec --localstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/var --sharedstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/com --mandir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/man --infodir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/info --enable-debug --enable-static-exe --disable-flto --disable-gost --with-ssl=/home/wouter/src/unbound/unbound-dist-EDtVCU/sslinstall --with-libexpat=/home/wouter/src/unbound/unbound-dist-EDtVCU/wxpinstall
Linked libs: event winsock (it uses WSAWaitForMultipleEvents), OpenSSL 1.1.1l  24 Aug 2021
Linked modules: dns64 respip validator iterator
scnr: that oudated openssl should count as a bug of its own
</details>

**Comment by wcawijngaards** [comment]
The code for this is in the connect_sslctx_create function, in util/net_help.c:1257-1283
https://github.com/NLnetLabs/unbound/blob/ed07c5424dd67d4eb851b8915b96cde3d7b2c45c/util/net_help.c#L1257-L1283

This means that it loads the certificate bundle from `tls-cert-bundle` first. And then, if `tls-win-cert` or `tls-system-cert` is enabled, it loads certificates from the system, both of these options set the `wincert` bool to true.

If I try to access the site you mention from here, it works with the system certs, on Linux. But also if I disable the system certs and load the tls-cert-bundle by itself. This is the same code that is used on both Linux and Windows, in that if the wincert option is false it does not do that. Since it works with code that is the same for Linux and Windows here, perhaps this is not windows specific but a certificate failure somehow?

**Comment by Tabiskabis** [comment]
Indeed it was a certifcate failure. I tried a ton of things and suddenly it was like the issue never existed. Probably an outdated certifcate in my system's ~bundle~ cert-store.
