### ISSUE TITLE
make ERROR netevent.h:1073:32: error: field 'blocked_pkt_pi' has incomplete type

### ISSUE THREAD

**Issue by TrueSEClab** [NLnetLabs/unbound#861]
make ERROR on branch `dnsoverquic`

`/configure --enable-debug --disable-gost --disable-flto --enable-tfo-client --enable-static-exe --enable-dnscrypt --enable-cachedb --with-ssl --with-libexpat=/usr --with-libhiredis --with-libsodium=/mingw64
`
~~~ cmd
# make
./libtool --tag=CC --mode=compile gcc -I.  -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o dns.lo -c services/cache/dns.c
libtool: compile:  gcc -I. -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/dns.c  -DDLL_EXPORT -DPIC -o .libs/dns.o
libtool: compile:  gcc -I. -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/dns.c -o dns.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o infra.lo -c services/cache/infra.c
libtool: compile:  gcc -I. -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/infra.c  -DDLL_EXPORT -DPIC -o .libs/infra.o
In file included from ./services/cache/infra.h:50,
                 from services/cache/infra.c:46:
./util/netevent.h:1073:32: error: field 'blocked_pkt_pi' has incomplete type
 1073 |         struct ngtcp2_pkt_info blocked_pkt_pi;
      |                                ^~~~~~~~~~~~~~
make: *** [Makefile:323: infra.lo] Error 1
~~~

**Comment by wcawijngaards** [comment]
The compile did not set the libngtcp2 library, the implementation uses that for the quic protocol. There is an include of the ngtcp2.h header file above that failed error, but only if NGTCP2 is enabled. The library can be added to configure with --with-libngtcp2. Also then use libopenssl+quic for openssl, there are install instructions on the libngtcp2 page.

The compile without quic failed, and this is an error for the branch. Thanks for the report! The commit fixes it so that without quic it works.
