### ISSUE TITLE
[FR] Use kernel timestamps for dnstap

### ISSUE THREAD

**Issue by edmonds** [NLnetLabs/unbound#888]
Hey @wcawijngaards @vvfedorenko, I see support was added for kernel timestamping of client queries in https://github.com/NLnetLabs/unbound/pull/882. Looks like it's conditionally enabled only if the new `sock_queue_timeout` option is enabled?

Any chance the kernel timestamp could be enabled and used (if available) instead of re-fetching the timestamp in the dnstap code?

https://github.com/NLnetLabs/unbound/blob/1fb78afc291a72f2a69f2c8215e36428d5bfb8f8/dnstap/dnstap.c#L396

The dnstap code is going to run some time after the client query packet hits the machine, potentially after many context switches, etc., so the accuracy of the dnstap timestamp can certainly suffer if the query is being re-timestamped after getting the packet from the kernel.

Thanks!

**Comment by wcawijngaards** [comment]
Hi Robert, I have implemented the feature in the commit. It changes the kernel timestamp handling, so that the timestamp is not modified by the checking code, it is left as it was when the packet entered. The wait_queue_time that is calculated is used instead to measure if the packet needs to be dropped. Then the kernel timestamp is passed to dnstap, and if such a timestamp is available that is used for logging the client queries.

I hope this provides more accurate time information! The commit is part of the code repository.
