### ISSUE TITLE
EDNS_DO bit is always set for iterative queries

### ISSUE THREAD

**Issue by sattler** [NLnetLabs/unbound#918]
**Describe the bug**
Unbound sets the EDNS_DO bit even when DNSSEC validation is turned off. It seems like DO is always set when EDNS is activated.
This puts unnecessary burden on the network and name servers as DNSSEC might trigger truncated messages and a TCP fallback is triggered.

**To reproduce**
1. set `module-config: "iterator"` to disable the validator and remove all trust anchors (basically follow [How-to-turnoff-DNSSEC](https://www.nlnetlabs.nl/documentation/unbound/howto-turnoff-dnssec/)
2. issue a DNS query `dig somedomayn.example.com @localhost`
3. Unbound will set the DO bit in EDNS for outgoing queries towards authoritative nameservers

**Expected behavior**
Unbound should not set the DO bit when DNSSEC validation is turned off and the client query did not set the DO bit

**System:**
 - Unbound version: 1.17.2
 - OS: Debian GNU/Linux 10 (buster)
 - `unbound -V` output:
 ```
 Version 1.17.2

Configure line: --with-libevent --prefix /*/unbound/build-local
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Comment by sattler** [comment]
https://github.com/NLnetLabs/unbound/blob/master/iterator/iterator.c#L2832 seems to be the reason for this behavior. ENDS_DO is always set

**Comment by wcawijngaards** [comment]
Unbound fetches the RRSIGs and DNSSEC content always, and this is because a downstream client may be a DNSSEC validator. And these would require the signatures to be able to verify the responses. Unbound caches the query with the signatures. This is why unbound sets the DO flag. Also, unbound supports receiving the DNSSEC content if the upstream has this available, in that Unbound can parse and store the information, and possibly usefully for future responses to clients that want this information, so the setting of the flag that enables the upstream to include security information is useful.

This is not so much a burden on the network, the content is useful for security verification of the DNS information, and likely needs to be fetched, at some point, anyway. Unbound was written to act as a validator and support DNSSEC from the start.

**Comment by sattler** [comment]
Thank you for your answer. I somewhat disagree with the interpretation on the network impact as in our case it is relevant (for now we will use a custom patched build - we are aware of the security properties of DNSSEC but specifically don't want it in our case).

Wouldn't a downstream client set the DO bit itself and unbound could use that when DNSSEC is otherwise disabled within the unbound configuration itself?

**Comment by wcawijngaards** [comment]
Really, is it the use of TCP? The network has trouble with TCP? Or is there trouble with fragments? Is there some problem with the TCP setting or EDNS size settings in the config of Unbound? It is designed to have very minimal packet size, so these troubles should not happen? Also, the network should really be configured so that the, occasional, TCP connection actually works. There is a bunch of documents that advise this, as well.

Also, disabling this makes it impossible for downstream clients to use DNSSEC. And Unbound has these settings to help the deployment of DNSSEC. Making it impossible to get the content, or wait for another roundtrip to fetch the information is making it hard to have DNSSEC verification for the downstream end users. To have this deployment there is a variety of measures considered, also stuff like including DNS records in website certificates, and much more. So I think it would be nice if the feature would remain enabled, as this will facilitate a more secure network for the users of the service.

For this reason, waiting until the downstream client sets a DO flag, to fetch the DNSSEC information, is not the strategy that is coded into Unbound. Unbound fetches the necessary information straight away, paving the possibility for every client to get the DNSSEC information as fast as possible.

**Comment by abh** [comment]
We ran into the problem in the context of DNS64.

- Unbound is running on the client device; DNSSEC disabled.
- Unbound speaks to an upstream resolver doing DNS64.
- Since the DO flag is always set, the upstream resolver doesn't synthesize the AAAA records (expecting that the client would just reject it anyway with an even more confusing error)
- Network is IPv6-only with NAT64/DNS64, so ... no connectivity.

**Comment by wcawijngaards** [comment]
There is an option, that was added recently, called `disable-edns-do: yes` that disables EDNS DO from being sent, that could perhaps help. Or get unbound to do the DNS64 synthesis, with "dns64 " prefixed in module-config and the `dns64-prefix: 64:ff9b::0/96` option.

**Comment by sattler** [comment]
Thank you for adding this option! This solves our problem
