### ISSUE TITLE
unbound 1.18.0 make test error

### ISSUE THREAD

**Issue by oukb** [NLnetLabs/unbound#927]
Hi

Unbound 1.18.0
make test error on Centos/RHEL 8/9

```
Aug 31 09:54:47 unbound[11727:0] debug: query took 0.000000 sec
Aug 31 09:54:47 unbound[11727:0] info: mesh_run: end 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 1 recursion replies sent, 0 replies dropped, 0 states jostled out
Aug 31 09:54:47 unbound[11727:0] info: average recursion processing time 0.000000 sec
Aug 31 09:54:47 unbound[11727:0] info: histogram of recursion processing times
Aug 31 09:54:47 unbound[11727:0] info: [25%]=0 median[50%]=0 [75%]=0
Aug 31 09:54:47 unbound[11727:0] info: lower(secs) upper(secs) recursions
Aug 31 09:54:47 unbound[11727:0] info:    0.000000    0.000001 1
Aug 31 09:54:47 unbound[11727:0] debug: cache memory msg=67215 rrset=68862 infra=7904 val=66591 subnet=74536
Aug 31 09:54:47 unbound[11727:0] info: testbound: end of event stage
Aug 31 09:54:47 unbound[11727:0] debug: comparepkt: 
Aug 31 09:54:47 unbound[11727:0] debug: bad EDE INFO-CODE. Expected: 6, and got: 7

Aug 31 09:54:47 unbound[11727:0] info: testbound: do STEP 20 CHECK_ANSWER
Aug 31 09:54:47 unbound[11727:0] fatal error: testbound: not matched 
./testdata/autotrust_init_failsig.rpl  failed
```

Logs:
https://download.copr.fedorainfracloud.org/results/fcsm/unbound/epel-8-x86_64/06358703-unbound/builder-live.log.gz
https://download.copr.fedorainfracloud.org/results/fcsm/unbound/epel-9-x86_64/06358703-unbound/builder-live.log.gz

and no error on fedora 37-39:
https://download.copr.fedorainfracloud.org/results/fcsm/unbound/fedora-38-x86_64/06358703-unbound/builder-live.log.gz

**Comment by wcawijngaards** [comment]
The commit fixes it, by changing the test to be lenient for SHA1 support. Without SHA1 the DNSSEC failure EDE error code differs from when there is SHA1 support, and this caused the test to error out. The change allows the different EDE code.

Likely this is what causes the difference, depending on the platforms support. The issue should be fixed with this. The issue can be replicated with `--disable-sha1`. Thanks for the report!
