### ISSUE TITLE
enforcing clang-format?

### ISSUE THREAD

**Issue by chantra** [NLnetLabs/unbound#96]
I am not sure what formatting is used by unbound code base, and failed to find guidance, but I know that any time I do work on it, I have to disable auto-formatting in my editor or I get huge diffs which are mostly dealing with whitespaces.

I don't really mind what formatting is used, but I like not to have to care about and letting my text editor do it for me :)

I think `clang-format` is rather widely adopted, and would like to suggest it for unbound. But in the end, whatever is used as long as it is easy to find guidance as to what to use. Possibly with macros or whatever that allow easy discovery.

What do you think?

**Comment by wcawijngaards** [comment]
So the formatting used by Unbound (and also NSD by the way) is the formatting, per file or per piece of file that that author made.  And I am loath to change it, because I do not want to unsettle the code. So based on where you insert the code I would want it to fit in nice.  So this explains what the formatting is like today.  And also why I do not really want to change it to a programmatic output, I prefer the original formatting and code additions looking good to match it.
Probably the format tool if it only adjusted the code that is being added, not all the rest of it, would be less intrusive, and look nice. (autoindent and smartindent work fine for me, by the way).

**Comment by chantra** [comment]
Thanks @wcawijngaards , yeah unfortunately, tools a la clang-format work on the whole file AFAIK.

Yeah, the diffs when formatting is applied is a bit painful, typically one would want to get the whole repo formatted in 1 commit. It does mess the blame a bit too, but then from there on, it makes formatting a no-brainer.

> autoindent and smartindent work fine for me, by the way

yeah, I typically disable auto-formatting when doing stuff on unbound code base and let the formatting happening. In any cases, thought it was worth suggesting `clang-format`.

**Comment by wcawijngaards** [comment]
I agree with closing the issue here, but as an FYI, after looking up documentation on `clang-format`, it can be toggled with comments (`/* clang-format off */` and `/* clang-format on */`) and with commandline options for byteranges or `-lines=<start line>:<end line>`.  Just to expose the feature, it seems very feature-rich by the way, but I still don't want a project wide format-wipe.  This kind of thing works better if you have it enabled at project start and have check-in tests, for Unbound this is something I did with splint and later code analysis features, and that kept the number of code anomalies down, on a commit-by-commit effort.
