### ISSUE TITLE
TCP returns, UDP does not (Docker, gluetun)

### ISSUE THREAD

**Issue by ezekieldas** [NLnetLabs/unbound#960]
I realize this isn't entirely an Unbound issue yet I'd be most grateful if someone could offer some insight on this. While I understand the fundamentals between TCP and UDP I've exhausted my knowledge here. 

In short, my TCP based requests come back as expected. However UDP are attempting to return at the tun0 VPN interface. I don't see what could be causing this. I've examined the unbound.conf carefully, read through the docs hoping to find something that might have an impact, yet empty handed. 

My tests involve:
```
tcp request: dig @192.168.1.90 asdf.com -p 5353 +tcp
udp request: dig @192.168.1.90 asdf.com -p 5353
```
```
/ # tcpdump -n -i any port 53
tcpdump: data link type LINUX_SLL2
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
00:06:44.116864 lo    In  IP 127.0.0.1.37510 > 127.0.0.1.53: 44369+ [1au] A? cloudflare.com. (43)
00:06:44.116944 lo    In  IP 127.0.0.1.53 > 127.0.0.1.37510: 44369 2/0/1 A 104.16.132.229, A 104.16.133.229 (75)
00:06:46.283721 eth0  In  IP 192.168.1.90.46875 > 172.22.0.2.53: Flags [S], seq 1490396862, win 64660, options [mss 1220,sackOK,TS val 991358628 ecr 0,nop,wscale 7], length 0
00:06:46.283750 eth0  Out IP 172.22.0.2.53 > 192.168.1.90.46875: Flags [S.], seq 369573755, ack 1490396863, win 65160, options [mss 1460,sackOK,TS val 2963301563 ecr 991358628,nop,wscale 7], length 0
00:06:46.283767 eth0  In  IP 192.168.1.90.46875 > 172.22.0.2.53: Flags [.], ack 1, win 506, options [nop,nop,TS val 991358628 ecr 2963301563], length 0
00:06:46.283815 eth0  In  IP 192.168.1.90.46875 > 172.22.0.2.53: Flags [P.], seq 1:52, ack 1, win 506, options [nop,nop,TS val 991358628 ecr 2963301563], length 51 16899+ [1au] A? asdf.com. (49)
00:06:46.283829 eth0  Out IP 172.22.0.2.53 > 192.168.1.90.46875: Flags [.], ack 52, win 509, options [nop,nop,TS val 2963301563 ecr 991358628], length 0
00:06:46.283959 eth0  Out IP 172.22.0.2.53 > 192.168.1.90.46875: Flags [P.], seq 1:56, ack 52, win 509, options [nop,nop,TS val 2963301563 ecr 991358628], length 55 16899 1/0/1 A 205.196.223.8 (53)
00:06:46.283978 eth0  In  IP 192.168.1.90.46875 > 172.22.0.2.53: Flags [.], ack 56, win 506, options [nop,nop,TS val 991358628 ecr 2963301563], length 0
00:06:46.284188 eth0  In  IP 192.168.1.90.46875 > 172.22.0.2.53: Flags [F.], seq 52, ack 56, win 506, options [nop,nop,TS val 991358628 ecr 2963301563], length 0
00:06:46.284239 eth0  Out IP 172.22.0.2.53 > 192.168.1.90.46875: Flags [F.], seq 56, ack 53, win 509, options [nop,nop,TS val 2963301563 ecr 991358628], length 0
00:06:46.284258 eth0  In  IP 192.168.1.90.46875 > 172.22.0.2.53: Flags [.], ack 57, win 506, options [nop,nop,TS val 991358628 ecr 2963301563], length 0
---
00:06:49.258249 lo    In  IP 127.0.0.1.58032 > 127.0.0.1.53: 40654+ [1au] A? cloudflare.com. (43)
00:06:49.258374 lo    In  IP 127.0.0.1.53 > 127.0.0.1.58032: 40654 2/0/1 A 104.16.132.229, A 104.16.133.229 (75)
00:06:50.226397 eth0  In  IP 192.168.1.90.39234 > 172.22.0.2.53: 5167+ [1au] A? asdf.com. (49)
00:06:50.226519 tun0  Out IP 172.25.72.56.53 > 192.168.1.90.39234: 5167 1/0/1 A 205.196.223.8 (53)
00:06:52.228783 eth0  In  IP 192.168.1.90.49060 > 172.22.0.2.53: 5167+ [1au] A? asdf.com. (49)
00:06:52.228902 tun0  Out IP 172.25.72.56.53 > 192.168.1.90.49060: 5167 1/0/1 A 205.196.223.8 (53)
00:06:54.231099 eth0  In  IP 192.168.1.90.38072 > 172.22.0.2.53: 5167+ [1au] A? asdf.com. (49)
00:06:54.231250 tun0  Out IP 172.25.72.56.53 > 192.168.1.90.38072: 5167 1/0/1 A 205.196.223.8 (53)
00:06:54.399788 lo    In  IP 127.0.0.1.34358 > 127.0.0.1.53: 23570+ [1au] A? cloudflare.com. (43)
00:06:54.399866 lo    In  IP 127.0.0.1.53 > 127.0.0.1.34358: 23570 2/0/1 A 104.16.133.229, A 104.16.132.229 (75)
00:06:59.541531 lo    In  IP 127.0.0.1.51256 > 127.0.0.1.53: 22681+ [1au] A? cloudflare.com. (43)
00:06:59.541621 lo    In  IP 127.0.0.1.53 > 127.0.0.1.51256: 22681 2/0/1 A 104.16.133.229, A 104.16.132.229 (75)
```

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
    volumes:
      - /usr/local/docker/gluetun/gluetun_config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<key>
      - WIREGUARD_ADDRESSES=172.25.72.56/32
      - VPN_ENDPOINT_PORT=2049
```

**Comment by wcawijngaards** [comment]
Quite likely what is happening is that the tunnel updates the routing tables. When a UDP response is returned, unbound performs a plain UDP send to the destination, that is the same as the address it came from. But the response passes through the routing tables to find out what interface to use for that destination. For TCP, this is set up when the connection is established. But for UDP the response packet is its own packet going through that routing table, and depending on the routing table setup a destination, like a router endpoint or interface is chosen. If a route is added that takes the traffic to that destination then that is where the response for the UDP query goes. Perhaps the tunnel setup updates the traffic selection methods, and then the traffic for certain destinations ends up there.

There are several possible solutions. One is to configure unbound to specifically bind to interfaces, eg by IP address, so that the routing is unambiguous because of that selection. The return packet then does not start at a point that can be determined because it was fixated by the interface selection, by using the interface: config option, possibly several times. Another, solution could be, and likely is more useful in this case, to enable `interface-automatic: yes` in unbound.conf. With that unbound stores the incoming query information, including source and destination, and uses that for the return reply, it is then possible that the extra information causes the network to select a different interface for the destination traffic.

Another solution could be to modify the route table or other network interface selection strategies to pick the correct interface or source IP address for the replies, for the particular communication endpoint that the query is made from.

**Comment by ezekieldas** [comment]
My initial tests are showing `interface-automatic: yes` is a perfect solution here. I regret overlooking that in [the documentation](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html)! 

Thank you very much for the detailed and prompt reply.

I'm going to run a few more tests/configurations and will update this issue with some closing comments. I'll also inform [gluetun](https://github.com/qdm12/gluetun) of this finding.

**Comment by ezekieldas** [comment]
I've tested this option with a couple of Unbound containers (mvance/unbound, cdrocker/unbound). I found that applying only the one additional option  `interface-automatic: yes` to either container scenario resulted in positive results (ie, return of UDP on originating interface). 

Closing this out with big thanks to [wcawijngaards](https://github.com/wcawijngaards)!
